use super::*;
use alloy::primitives::{address, b256};

// Committed `registerNode` ownership vector from
// `contracts/test/CapacityBondRegionE2E.t.sol` (generated by
// `contracts/test/ed25519-vectors`). The published ed25519 signature
// verifies against the nodeId only if our digest byte-matches the
// contract's — a true differential check against the authoritative
// on-chain encoding, not a self-consistent round-trip.
const REG_NODE_ID: B256 = b256!("d04ab232742bb4ab3a1368bd4615e4e6d0224ab71a016baf8520a332c9778737");
const REG_OPERATOR: Address = address!("f39Fd6e51aad88F6F4ce6aB8827279cffFb92266");
const REG_CHAIN_ID: u64 = 31_337;
const REG_NONCE: u64 = 0;
const REG_ED25519_SIG: [u8; 64] = [
    0x2d, 0x1b, 0x18, 0x05, 0xfe, 0x88, 0x07, 0x82, 0xcc, 0x1b, 0x60, 0xbc, 0x49, 0xf7, 0xd1, 0xe2,
    0x74, 0x45, 0x87, 0x0c, 0x01, 0xe1, 0xde, 0x19, 0x59, 0x80, 0x97, 0x0a, 0x65, 0xf4, 0xe0, 0xc7,
    0xfa, 0x9e, 0xa3, 0x03, 0x47, 0xbb, 0x87, 0x6c, 0x4b, 0x1c, 0xe6, 0x41, 0x74, 0xfd, 0x8d, 0x6a,
    0x2b, 0x90, 0x52, 0x0d, 0x7e, 0xd4, 0xde, 0xa1, 0x2d, 0x80, 0x5d, 0x40, 0x1e, 0xa5, 0xe4, 0x05,
];

#[test]
fn ownership_digest_matches_published_vector() {
    let digest = ownership_message_digest(REG_NODE_ID, REG_OPERATOR, REG_CHAIN_ID, REG_NONCE);

    // The vector's signature is a strict-valid ed25519 signature over the
    // contract's ownership digest, with the public key equal to the nodeId.
    // If our digest is wrong, verification fails.
    let pubkey = iroh::PublicKey::from_bytes(REG_NODE_ID.as_slice().try_into().unwrap())
        .expect("nodeId is a valid ed25519 public key");
    let sig = iroh::Signature::from_bytes(&REG_ED25519_SIG);
    pubkey
        .verify(digest.as_slice(), &sig)
        .expect("published ed25519 signature must verify against our digest");
}

#[test]
fn ownership_digest_is_nonce_sensitive() {
    let d0 = ownership_message_digest(REG_NODE_ID, REG_OPERATOR, REG_CHAIN_ID, 0);
    let d1 = ownership_message_digest(REG_NODE_ID, REG_OPERATOR, REG_CHAIN_ID, 1);
    assert_ne!(d0, d1, "registrationNonce must feed the digest");
}

#[test]
fn pack_multiaddrs_length_prefixes_big_endian() {
    let packed = pack_multiaddrs(&["/ip4/203.0.113.10/udp/4433/quic-v1".to_string()]).unwrap();
    let body = "/ip4/203.0.113.10/udp/4433/quic-v1".as_bytes();
    let len = u16::try_from(body.len()).unwrap();
    assert_eq!(&packed[0..2], &len.to_be_bytes(), "BE uint16 length prefix");
    assert_eq!(&packed[2..], body, "body follows the prefix verbatim");
}

#[test]
fn pack_multiaddrs_concatenates_entries() {
    let packed = pack_multiaddrs(&["aa".to_string(), "bbbb".to_string()]).unwrap();
    // (len=2, "aa") then (len=4, "bbbb").
    assert_eq!(
        packed,
        vec![0x00, 0x02, b'a', b'a', 0x00, 0x04, b'b', b'b', b'b', b'b']
    );
}

#[test]
fn pack_multiaddrs_empty_is_empty() {
    assert!(pack_multiaddrs(&[]).unwrap().is_empty());
}

#[test]
fn unpack_multiaddrs_round_trips() {
    let addrs = vec![
        "/ip4/203.0.113.10/udp/4433/quic-v1".to_string(),
        "/ip6/2001:db8::1/udp/4433/quic-v1".to_string(),
    ];
    let packed = pack_multiaddrs(&addrs).unwrap();
    assert_eq!(unpack_multiaddrs(&packed).unwrap(), addrs);
}

#[test]
fn unpack_multiaddrs_empty_is_empty() {
    assert!(unpack_multiaddrs(&[]).unwrap().is_empty());
}

/// A truncated field must error rather than yield a short list: the eth
/// rotation path re-registers whatever this returns, so a silent drop would
/// put a node back on-chain missing an address it had.
#[test]
fn unpack_multiaddrs_rejects_truncation() {
    // Length prefix with no body at all.
    assert!(unpack_multiaddrs(&[0x00]).is_err());
    // Prefix claims 4 bytes, only 2 follow.
    assert!(unpack_multiaddrs(&[0x00, 0x04, b'a', b'b']).is_err());
}

#[test]
fn unpack_multiaddrs_rejects_non_utf8() {
    assert!(unpack_multiaddrs(&[0x00, 0x01, 0xFF]).is_err());
}

#[test]
fn pack_multiaddrs_rejects_oversized_entry() {
    let huge = "x".repeat(usize::from(u16::MAX) + 1);
    let err = pack_multiaddrs(&[huge]).unwrap_err();
    assert!(err.to_string().contains("exceeds the uint16"), "{err}");
}

#[test]
fn decode_dial_addrs_parses_ip4_and_ip6() {
    let packed = pack_multiaddrs(&[
        "/ip4/203.0.113.10/udp/4433/quic-v1".to_string(),
        "/ip6/2001:db8::1/udp/4434/quic-v1".to_string(),
    ])
    .unwrap();
    let addrs = decode_dial_addrs(&packed);
    assert_eq!(
        addrs,
        vec![
            "203.0.113.10:4433".parse().unwrap(),
            "[2001:db8::1]:4434".parse().unwrap(),
        ]
    );
}

#[test]
fn decode_dial_addrs_ignores_trailing_segments() {
    let packed =
        pack_multiaddrs(&["/ip4/203.0.113.10/udp/4433/quic-v1/p2p/abc".to_string()]).unwrap();
    assert_eq!(
        decode_dial_addrs(&packed),
        vec!["203.0.113.10:4433".parse().unwrap()]
    );
}

#[test]
fn decode_dial_addrs_skips_malformed_entries_keeps_valid() {
    // A TCP multiaddr, a family mismatch, and a garbage string are each
    // dropped; the one well-formed QUIC entry survives.
    let packed = pack_multiaddrs(&[
        "/ip4/203.0.113.10/tcp/4433".to_string(),
        "/ip4/::1/udp/4433/quic-v1".to_string(),
        "not-a-multiaddr".to_string(),
        "/ip4/198.51.100.7/udp/5000/quic-v1".to_string(),
    ])
    .unwrap();
    assert_eq!(
        decode_dial_addrs(&packed),
        vec!["198.51.100.7:5000".parse().unwrap()]
    );
}

#[test]
fn decode_dial_addrs_empty_and_malformed_framing_yield_empty() {
    // Empty field → no hints.
    assert!(decode_dial_addrs(&[]).is_empty());
    // A lone byte cannot even hold a 2-byte length prefix → no hints, never
    // a panic: a torn record must not remove a peer from the dial set.
    assert!(decode_dial_addrs(&[0x00]).is_empty());
    // A length prefix (0x0004 = 4) that overruns the 2-byte body stops the
    // walk with nothing decoded before it.
    assert!(decode_dial_addrs(&[0x00, 0x04, b'a', b'b']).is_empty());
}

#[test]
fn decode_dial_addrs_recovers_per_entry_around_a_non_utf8_entry() {
    // A valid QUIC entry, a framing-intact but non-UTF8 entry, then another
    // valid QUIC entry. `unpack_multiaddrs` would error on the non-UTF8
    // entry and drop everything; the per-entry walk keeps both valid ones.
    let mut packed =
        pack_multiaddrs(&["/ip4/203.0.113.10/udp/4433/quic-v1".to_string()]).expect("pack first");
    // A hand-framed non-UTF8 entry: 2-byte big-endian length 1, then 0xFF.
    packed.extend_from_slice(&[0x00, 0x01, 0xFF]);
    packed.extend_from_slice(
        &pack_multiaddrs(&["/ip4/198.51.100.7/udp/5000/quic-v1".to_string()]).expect("pack third"),
    );
    assert_eq!(
        decode_dial_addrs(&packed),
        vec![
            "203.0.113.10:4433".parse().expect("addr 1"),
            "198.51.100.7:5000".parse().expect("addr 2"),
        ]
    );
}
