//! `CapacityBond` contract ABI bindings (ADR 003 § Node Registry, ADR 019).
//!
//! Generated by the `alloy::sol!` macro from the Solidity surface in
//! `contracts/src/CapacityBond.sol`. The read paths the node runtime
//! consumes plus the `registerNode` write path and its two nonce getters
//! (consumed by `decdn node register`, ADR 019 § Step 2.3) are mirrored —
//! see the macro body below for the exact surface. Two gotchas worth
//! flagging here rather than at the call site:
//!
//! - `getActiveNodes` returns `_registeredAddrs` unfiltered (the
//!   contract's own comment at its definition documents this); callers
//!   must combine with `isActive(operator)` for the strict
//!   "registered AND bond ≥ minBond AND no unbonding AND not ejected"
//!   predicate.
//! - `nodeIdOf` returns `(bytes32 nodeId, bool active)` where the bool
//!   is the full `isActive` predicate, not a separate "registered"
//!   flag.

// The `sol!`-generated bindings include macro-emitted code that uses
// patterns workspace clippy denies (raw indexing into ABI fixed-size
// byte arrays, `unwrap` on infallible conversions). These allows scope
// the relaxation to this module only.
#[allow(
    clippy::expect_used,
    clippy::indexing_slicing,
    clippy::panic,
    clippy::unwrap_used,
    clippy::pub_underscore_fields,
    clippy::missing_docs_in_private_items,
    clippy::too_many_arguments,
    missing_debug_implementations,
    missing_docs,
    non_snake_case,
    non_camel_case_types
)]
mod sol_types {
    alloy::sol! {
        #[sol(rpc)]
        contract CapacityBond {
            // -----------------------------------------------------------------
            // Structs
            // -----------------------------------------------------------------

            /// Per-operator registration record. Mirrors the on-chain
            /// struct at `contracts/src/CapacityBond.sol`. Field
            /// order is part of the ABI; do not rearrange.
            struct NodeInfo {
                bytes32 nodeId;
                address ethAddress;
                bool active;
                uint64 lastMultiaddrUpdate;
                bytes multiaddrs;
                string regionHint;
            }

            // -----------------------------------------------------------------
            // View functions (only those consumed by the node runtime)
            // -----------------------------------------------------------------

            /// Full active-bonder predicate: registered AND
            /// `activeBond ≥ minBond` AND no unbonding request in
            /// flight AND not ejected.
            function isActive(address operator) external view returns (bool);

            /// `nodeId`-keyed convenience over `isActive`.
            function isActiveNode(bytes32 nodeId) external view returns (bool);

            /// Operator → `(nodeId, isActive)`. `nodeId` is
            /// `bytes32(0)` if the operator has no binding.
            function nodeIdOf(address operator) external view returns (bytes32 nodeId, bool active);

            /// Paginated snapshot of `_registeredAddrs` — every
            /// operator with a current registration, **NOT** filtered
            /// for bond / unbonding / ejection. Callers combine with
            /// `isActive(operator)` to get the strict active set.
            function getActiveNodes(uint256 offset, uint256 limit) external view returns (NodeInfo[] memory);

            /// Cardinality of `_registeredAddrs`.
            function getActiveNodeCount() external view returns (uint256);

            /// Per-operator EIP-712 `BindNodeId` nonce. Feeds the
            /// `bindingSignature` digest at registration time (ADR 019
            /// § Step 2.3). `0` for an operator that has never bound.
            function bindingNonce(address operator) external view returns (uint64);

            /// Per-nodeId registration nonce. Feeds the ed25519
            /// ownership-proof digest (ADR 019 § Step 2.3); incremented on
            /// deregistration / rebinding so a fresh signature is required on
            /// re-onboarding. `0` for a never-registered nodeId.
            function registrationNonce(bytes32 nodeId) external view returns (uint64);

            // -----------------------------------------------------------------
            // Node registry write path (ADR 019 § Step 2.3)
            // -----------------------------------------------------------------

            /// Atomically bind `nodeId` ↔ `msg.sender` and activate the node.
            /// Verifies the EIP-712 `bindingSignature` over
            /// `BindNodeId(nodeId, bindingNonce[msg.sender])` and the ed25519
            /// `ed25519Signature` over the ownership digest
            /// (`decdn_incentive::node_register::ownership_message_digest`).
            /// Reverts if the operator's bond is below `minBond` / the
            /// declared-capacity curve — Phase 2.1/2.2 (`bond` / `declareMbps`)
            /// are a precondition.
            function registerNode(
                bytes32 nodeId,
                bytes multiaddrs,
                string regionHint,
                bytes bindingSignature,
                bytes ed25519Signature
            ) external;

            // -----------------------------------------------------------------
            // Events that mutate active-set membership
            // -----------------------------------------------------------------

            /// Node activated via `registerNode`. `nodeId`-indexed.
            event NodeRegistered(
                bytes32 indexed nodeId,
                address indexed ethAddress,
                bytes multiaddrs,
                string regionHint,
                uint64 bindingNonce,
                uint64 registrationNonce
            );

            /// Node deactivated via `deregisterNode`. `nodeId`-indexed.
            event NodeDeregistered(bytes32 indexed nodeId);

            /// Node deactivated by `slash` or `ejectNode` dropping
            /// bond below `minBond / 2`. `nodeId`-indexed.
            event NodeAutoEjected(bytes32 indexed nodeId, uint256 remainingBond);

            /// Node deactivated by `ContentBlacklist`-role caller.
            /// **Operator-indexed** — translate via `nodeIdOf`.
            event EjectedByBlacklist(address indexed operator);

            /// Previously ejected operator brought bond back to
            /// `minBond` via `bond()`. **Operator-indexed** —
            /// translate via `nodeIdOf`.
            event Reinstated(address indexed operator);

            /// Operator requested unbonding; flips `isActive` to
            /// `false` immediately even though the operator stays in
            /// `_registeredAddrs`. **Operator-indexed** — translate
            /// via `nodeIdOf`.
            event UnbondingRequested(
                address indexed operator,
                uint256 amount,
                uint256 unlockAt,
                uint256 newActiveBond
            );
        }
    }
}

pub use sol_types::CapacityBond;
