//! `ContentBlacklist` contract ABI bindings (ADR 011 § Content Takedown, ADR
//! 031 § `ContentBlacklist` appeal-contract surface).
//!
//! Generated by the `alloy::sol!` macro from the Solidity surface in
//! `contracts/src/ContentBlacklist.sol`. The node's blacklist compliance
//! watcher ([`crate`] consumer `decdn-node::blacklist_watcher`) consumes the
//! read path (`isHashBlacklistedForOperator`) plus the `HashBlacklisted` /
//! `HashRemoved` membership events: each event is a *signal to re-read* the
//! authoritative in-scope predicate for the hashes the node holds, then evict
//! any that are blacklisted for this operator (global ∪ current-region ∪
//! ripening-prev-region — the region logic lives entirely inside the contract
//! view, so the watcher never repacks a region).
//!
//! The write + `getHashEntry` surface is mirrored for the cross-layer e2e
//! harness (`decdn-e2e`), which drives governance blacklist adds and reads
//! `addedAt` to time the compliance / slashability windows.

// The `sol!`-generated bindings include macro-emitted code that uses patterns
// workspace clippy denies (raw indexing into ABI fixed-size byte arrays,
// `unwrap` on infallible conversions). These allows scope the relaxation to
// this module only.
#[allow(
    clippy::expect_used,
    clippy::indexing_slicing,
    clippy::panic,
    clippy::unwrap_used,
    clippy::pub_underscore_fields,
    clippy::missing_docs_in_private_items,
    clippy::too_many_arguments,
    missing_debug_implementations,
    missing_docs,
    non_snake_case,
    non_camel_case_types
)]
mod sol_types {
    alloy::sol! {
        #[sol(rpc)]
        contract ContentBlacklist {
            /// Per-(region, hash) entry. `addedAt == 0` means "not blacklisted";
            /// `suspended` is set while a fast-tracked appeal lifts enforcement.
            struct HashEntry {
                uint64 addedAt;
                bool suspended;
            }

            // -----------------------------------------------------------------
            // View functions (consumed by the node runtime)
            // -----------------------------------------------------------------

            /// True iff `hash` is an enforceable blacklist entry in scope for
            /// `operator`: global ∪ current-region ∪ (ripening-window)
            /// previous-region, per ADR 030. The single source of truth for the
            /// watcher's scope decision — the region packing / ripening math
            /// stays on-chain.
            function isHashBlacklistedForOperator(bytes32 hash, address operator)
                external
                view
                returns (bool);

            /// Raw `(addedAt, suspended)` entry for `(region, hash)`. Used by the
            /// e2e harness to time windows; the node relies on the operator-scope
            /// predicate above instead.
            function getHashEntry(bytes32 region, bytes32 hash)
                external
                view
                returns (HashEntry memory);

            /// True iff `origin` is blacklisted at the operator/origin level
            /// (ADR 011 § Hash Evasion and Origin Blacklisting). Read at boot to
            /// reconcile the deny-set, since the event tail alone cannot answer
            /// "was this address already blacklisted before my scan window".
            function isOriginBlacklisted(address origin) external view returns (bool);

            // -----------------------------------------------------------------
            // Write functions (governance — driven by the e2e harness)
            // -----------------------------------------------------------------

            /// Add `hash` to the global blacklist (`GOVERNANCE_ROLE`). `reason`
            /// is the free-form on-chain audit-trail note (DMCA/DSA notice id).
            function addHashGlobal(bytes32 hash, string reason) external;

            /// Add `hash` to `region`'s blacklist (`REGIONAL_BODY_ROLE`). `reason`
            /// is the free-form on-chain audit-trail note (DMCA/DSA notice id).
            function addHashRegional(bytes32 region, bytes32 hash, string reason) external;

            /// Remove `hash` from the global blacklist (`GOVERNANCE_ROLE`).
            function removeHashGlobal(bytes32 hash) external;

            // -----------------------------------------------------------------
            // Membership events (watcher re-read signals)
            // -----------------------------------------------------------------

            /// A `(region, hash)` entry was added (or re-added). `region` is
            /// `bytes32("GLOBAL")` for the global scope.
            ///
            /// These declarations MUST match `ContentBlacklist.sol` field-for-field,
            /// including parameters this watcher never reads. `topic0` is the keccak of
            /// the event signature, and the non-indexed params are the ABI-encoded data
            /// payload — so a drift in either breaks the watcher twice over: it matches
            /// no logs at all, and would mis-decode any it did match. It fails SILENTLY,
            /// as an empty deny-set, which reads exactly like "nothing is blacklisted"
            /// while the node serves content it is slashable for serving.
            ///
            /// `version` (the post-change `getBlacklistVersion()`, ADR 011 § Polling) and
            /// `reason` (the audit-trail note) are both unused here for that reason alone:
            /// they are part of the signature, so they are part of this declaration.
            event HashBlacklisted(bytes32 indexed region, bytes32 indexed hash, uint256 version, string reason);

            /// A `(region, hash)` entry was removed. `version` as above.
            event HashRemoved(bytes32 indexed region, bytes32 indexed hash, uint256 version);

            /// An appeal-driven suspend/resume flipped whether a still-present
            /// entry is enforced (`suspended` gates the contract's `_isLive`, and
            /// therefore `isHashBlacklistedForOperator`). Neither add nor remove,
            /// so it emits no `HashBlacklisted`/`HashRemoved` — without this event
            /// a resume is invisible until the next batched re-scope, and serving
            /// a re-enforced hash in that window is slashable. `version` as above.
            event HashSuspensionUpdated(
                bytes32 indexed region, bytes32 indexed hash, uint256 version, bool suspended
            );

            /// An origin/operator address entered or left the origin blacklist
            /// (ADR 011 § Hash Evasion and Origin Blacklisting).
            ///
            /// Deliberately carries NO `version` and is deliberately OUTSIDE the
            /// `getBlacklistVersion()` poll cycle (ADR 011 § Polling). A consumer
            /// therefore cannot use the version counter to detect that it missed
            /// one — it must scan the event tail on its own block-range cursor
            /// and reconcile against `isOriginBlacklisted` at boot.
            event OriginBlacklistUpdated(address indexed origin, bool blacklisted);
        }
    }
}

pub use sol_types::ContentBlacklist;
