//! `OriginAssignment` contract ABI bindings (ADR 011 § Origin Assignment
//! Authority, ADR 022 § FIND\_VALUE Flow "Origin discovery").
//!
//! Generated by the `alloy::sol!` macro from the Solidity surface in
//! `contracts/src/OriginAssignment.sol`. Only the read path + the
//! membership-mutating events the node's chain-backed origin directory
//! ([`crate`] consumer `decdn-node::dht::chain_origin_directory`) consumes are
//! mirrored. The directory keeps a `namespaceId → authorized-operator` cache
//! current from these events, falling back to `getOrigins` for the bootstrap
//! snapshot.
//!
//! Two surfaces, one contract:
//! - Per-namespace assignments: `AssignmentActivated` replaces the operator
//!   set for a namespace; `AssignmentRevoked` / `BlacklistedAssignmentPruned`
//!   remove a single operator.
//! - The default-open allow-list (`namespaceId == 0`): `DefaultOpenAllowlistUpdated`
//!   replaces it wholesale; `DefaultOpenOperatorAdded` / `DefaultOpenOperatorRemoved`
//!   move a single operator. `getOrigins(0)` reads it.

// The `sol!`-generated bindings include macro-emitted code that uses
// patterns workspace clippy denies (raw indexing into ABI fixed-size
// byte arrays, `unwrap` on infallible conversions). These allows scope
// the relaxation to this module only.
#[allow(
    clippy::expect_used,
    clippy::indexing_slicing,
    clippy::panic,
    clippy::unwrap_used,
    clippy::pub_underscore_fields,
    clippy::missing_docs_in_private_items,
    clippy::too_many_arguments,
    missing_debug_implementations,
    missing_docs,
    non_snake_case,
    non_camel_case_types
)]
mod sol_types {
    alloy::sol! {
        #[sol(rpc)]
        contract OriginAssignment {
            // -----------------------------------------------------------------
            // View functions (only those consumed by the node runtime)
            // -----------------------------------------------------------------

            /// Current authorized-origin operator addresses for a namespace.
            /// `namespaceId == 0` reads the DAO-maintained default-open
            /// allow-list. Returns the live `EnumerableSet` values.
            function getOrigins(uint256 namespaceId) external view returns (address[] memory);

            // -----------------------------------------------------------------
            // Per-namespace assignment events
            // -----------------------------------------------------------------

            /// A namespace's authorized-origin set was replaced wholesale with
            /// `operators` (governance-ratified activation of a pending
            /// proposal). Carries the full post-state, so the cache replaces.
            event AssignmentActivated(uint256 indexed namespaceId, address[] operators);

            /// A single `operator` was removed from `namespaceId`'s authorized
            /// set (by the namespace owner or governance).
            event AssignmentRevoked(
                uint256 indexed namespaceId,
                address indexed operator,
                address indexed by
            );

            /// A blacklisted `operator` was pruned from `namespaceId`'s
            /// authorized set. Same cache effect as a revoke (remove one).
            event BlacklistedAssignmentPruned(
                uint256 indexed namespaceId,
                address indexed operator,
                address indexed pruner
            );

            // -----------------------------------------------------------------
            // Default-open allow-list events (namespaceId == 0)
            // -----------------------------------------------------------------

            /// The default-open allow-list was replaced wholesale with
            /// `operators`. `updateIndex` is a monotonic version for observers.
            event DefaultOpenAllowlistUpdated(address[] operators, uint256 indexed updateIndex);

            /// A single `operator` was added to the default-open allow-list.
            event DefaultOpenOperatorAdded(address indexed operator);

            /// A single `operator` was removed from the default-open allow-list.
            event DefaultOpenOperatorRemoved(address indexed operator);
        }
    }
}

pub use sol_types::OriginAssignment;
