//! `OriginAssignment` contract ABI bindings (ADR 011 § Origin Assignment
//! Authority, ADR 022 § FIND\_VALUE Flow "Origin discovery").
//!
//! Generated by the `alloy::sol!` macro from the Solidity surface in
//! `contracts/src/OriginAssignment.sol`. Only the read path + the
//! membership-mutating events the node's chain-backed origin directory
//! ([`crate`] consumer `decdn-node::dht::chain_origin_directory`) consumes are
//! mirrored. The directory keeps a `namespaceId → authorized-operator` cache
//! current from these events, falling back to `getOrigins` for the bootstrap
//! snapshot.
//!
//! Assignments are per registered namespace: `AssignmentActivated` replaces the
//! operator set for a namespace; `AssignmentRevoked` /
//! `BlacklistedAssignmentPruned` remove a single operator. Namespace 0 has no
//! publisher and no authorized origins, so `getOrigins(0)` is always empty.

// The `sol!`-generated bindings include macro-emitted code that uses
// patterns workspace clippy denies (raw indexing into ABI fixed-size
// byte arrays, `unwrap` on infallible conversions). These allows scope
// the relaxation to this module only.
#[allow(
    clippy::expect_used,
    clippy::indexing_slicing,
    clippy::panic,
    clippy::unwrap_used,
    clippy::pub_underscore_fields,
    clippy::missing_docs_in_private_items,
    clippy::too_many_arguments,
    missing_debug_implementations,
    missing_docs,
    non_snake_case,
    non_camel_case_types
)]
mod sol_types {
    alloy::sol! {
        #[sol(rpc)]
        contract OriginAssignment {
            // -----------------------------------------------------------------
            // View functions (only those consumed by the node runtime)
            // -----------------------------------------------------------------

            /// Current authorized-origin operator addresses for a namespace.
            /// `namespaceId == 0` has no set and always returns empty. Returns
            /// the live `EnumerableSet` values.
            function getOrigins(uint256 namespaceId) external view returns (address[] memory);

            // -----------------------------------------------------------------
            // Write functions (publisher control plane, issue #1029)
            // -----------------------------------------------------------------

            /// Namespace owner proposes an authorized-origin operator set.
            /// Enters a pending state until governance activates it after the
            /// assignment timelock. Reverts if the caller is not the namespace
            /// owner, the set is empty/duplicated/over-cap, or an operator is
            /// not an active bonded node.
            function proposeAssignment(uint256 namespaceId, address[] operators) external;

            /// A pending assignment was proposed. `readyAt` is the unix time the
            /// timelock elapses (earliest governance activation).
            event AssignmentProposed(
                uint256 indexed namespaceId,
                address indexed proposer,
                address[] operators,
                uint256 readyAt
            );

            /// A pending proposal was cleared. `autoCleared == true` means a new
            /// `proposeAssignment` silently replaced a prior pending proposal.
            event AssignmentProposalCancelled(
                uint256 indexed namespaceId,
                address indexed proposer,
                bool autoCleared
            );

            // -----------------------------------------------------------------
            // Per-namespace assignment events
            // -----------------------------------------------------------------

            /// A namespace's authorized-origin set was replaced wholesale with
            /// `operators` (governance-ratified activation of a pending
            /// proposal). Carries the full post-state, so the cache replaces.
            event AssignmentActivated(uint256 indexed namespaceId, address[] operators);

            /// A single `operator` was removed from `namespaceId`'s authorized
            /// set (by the namespace owner or governance).
            event AssignmentRevoked(
                uint256 indexed namespaceId,
                address indexed operator,
                address indexed by
            );

            /// A blacklisted `operator` was pruned from `namespaceId`'s
            /// authorized set. Same cache effect as a revoke (remove one).
            event BlacklistedAssignmentPruned(
                uint256 indexed namespaceId,
                address indexed operator,
                address indexed pruner
            );
        }
    }
}

pub use sol_types::OriginAssignment;
