//! `OriginAssignment` contract ABI bindings (ADR 011 § Origin Assignment
//! Authority, ADR 022 § FIND\_VALUE Flow "Origin discovery").
//!
//! Generated by the `alloy::sol!` macro from the Solidity surface in
//! `contracts/src/OriginAssignment.sol`. Only the read path, the publisher
//! control-plane writes the CLI submits, and the membership-mutating events the
//! node's chain-backed origin directory ([`crate`] consumer
//! `decdn-node::dht::chain_origin_directory`) consumes are mirrored. The
//! directory keeps a `namespaceId → authorized-operator` cache current from
//! these events, falling back to `getOrigins` for the bootstrap snapshot.
//!
//! The contract has two planes. Whether a **publisher wallet** may seat origins
//! is decided by a swappable `IVettingPolicy` (governance re-points it with
//! `setVettingPolicy`); a vetted publisher then seats and unseats origins for
//! its own namespaces instantly, one operator at a time. So every event here is
//! a single-operator delta — `OriginAdded` seats one, `OriginRemoved` /
//! `BlacklistedOriginPruned` remove one — and the directory treats each as a
//! signal to re-read `getOrigins`, not as history. Namespace 0 has no publisher
//! and no authorized origins, so `getOrigins(0)` is always empty.
//!
//! The self-service `publish request-vetting` command targets the installed
//! policy, not this contract: it reads `OriginAssignment::vettingPolicy` and
//! calls `VettingRequestable::requestVetting` there. That call succeeds (a
//! timelocked policy queues a request and emits `VettingRequested`), no-ops, or
//! reverts `VettingRequestUnsupported` with a reason, per the installed policy.

// The `sol!`-generated bindings include macro-emitted code that uses
// patterns workspace clippy denies (raw indexing into ABI fixed-size
// byte arrays, `unwrap` on infallible conversions). These allows scope
// the relaxation to this module only.
#[allow(
    clippy::expect_used,
    clippy::indexing_slicing,
    clippy::panic,
    clippy::unwrap_used,
    clippy::pub_underscore_fields,
    clippy::missing_docs_in_private_items,
    clippy::too_many_arguments,
    missing_debug_implementations,
    missing_docs,
    non_snake_case,
    non_camel_case_types
)]
mod sol_types {
    alloy::sol! {
        #[sol(rpc)]
        contract OriginAssignment {
            // -----------------------------------------------------------------
            // View functions (only those consumed by the node runtime + CLI)
            // -----------------------------------------------------------------

            /// Current authorized-origin operator addresses for a namespace.
            /// `namespaceId == 0` has no set and always returns empty. Returns
            /// the live `EnumerableSet` values.
            function getOrigins(uint256 namespaceId) external view returns (address[] memory);

            /// How many namespaces currently have a non-empty authorized set.
            function assignedNamespaceCount() external view returns (uint256);

            /// A page of the namespaces that currently have origins. Membership
            /// within a namespace was always readable via `getOrigins`; this is
            /// the key set, whose absence was the sole reason a bootstrap had to
            /// replay the seating events from the deploy block.
            ///
            /// Order is NOT stable across mutations (swap-and-pop removal), so
            /// every page and the count it is checked against MUST be read at one
            /// pinned block height.
            function assignedNamespaces(uint256 offset, uint256 limit)
                external
                view
                returns (uint256[] memory);

            /// Whether the installed policy vets `publisher` to seat origins for
            /// its own namespaces. `addOrigin` reverts `PublisherNotVetted` while
            /// false. A passthrough to `vettingPolicy().isVetted(publisher)`.
            function isVettedPublisher(address publisher) external view returns (bool);

            /// The installed vetting authority. `publish request-vetting` reads
            /// this and calls `requestVetting()` on it (see [`VettingRequestable`]).
            function vettingPolicy() external view returns (address);

            // -----------------------------------------------------------------
            // Write functions (publisher control plane, issues #1029 / #1491)
            // -----------------------------------------------------------------

            /// Vetted namespace owner seats one more authorized origin. Instant:
            /// there is no pending state and no governance step. Reverts if the
            /// caller does not own the namespace, is not vetted, or the operator
            /// is not an active bonded node, is blacklisted, is already seated,
            /// or would exceed `maxOriginsPerNamespace`.
            function addOrigin(uint256 namespaceId, address operator) external;

            /// Namespace owner (own namespace) or governance (any) unseats one
            /// authorized origin. Instant; reverts if the operator is not seated.
            function removeOrigin(uint256 namespaceId, address operator) external;

            // -----------------------------------------------------------------
            // Per-namespace origin-membership events
            // -----------------------------------------------------------------

            /// One `operator` was seated as an authorized origin for
            /// `namespaceId` by its vetted publisher. The single "origin seated"
            /// event: there is no wholesale set replacement.
            event OriginAdded(
                uint256 indexed namespaceId,
                address indexed operator,
                address indexed by
            );

            /// A single `operator` was unseated from `namespaceId`'s authorized
            /// set (by the namespace owner or governance).
            event OriginRemoved(
                uint256 indexed namespaceId,
                address indexed operator,
                address indexed by
            );

            /// A blacklisted `operator` was pruned from `namespaceId`'s
            /// authorized set. Same cache effect as a removal (remove one).
            event BlacklistedOriginPruned(
                uint256 indexed namespaceId,
                address indexed operator,
                address indexed pruner
            );
        }

        /// The self-service vetting surface of whatever policy
        /// [`OriginAssignment::vettingPolicy`] currently points at (ADR 011,
        /// `contracts/src/interfaces/IVettingRequestable.sol` +
        /// `TimelockedGovernanceVettingPolicy`). `publish request-vetting` binds
        /// this at the policy address and calls `requestVetting()`:
        /// - a timelocked policy queues a request and emits `VettingRequested`;
        /// - a policy with no self-service path reverts `VettingRequestUnsupported`
        ///   with a caller-facing reason (the error is shared across policies so
        ///   the CLI decodes it without knowing which policy is installed);
        /// - a no-gate policy no-ops.
        #[sol(rpc)]
        contract VettingRequestable {
            function requestVetting() external;

            /// The installed policy grants vetting some other way; `reason`
            /// explains how (surfaced verbatim by the CLI).
            error VettingRequestUnsupported(string reason);

            /// A publisher queued a vetting request. `readyAt` is the unix time
            /// the timelock elapses (earliest governance grant). Emitted only by
            /// a timelocked policy.
            event VettingRequested(address indexed publisher, uint256 readyAt);
        }
    }
}

pub use sol_types::{OriginAssignment, VettingRequestable};
