//! `PaymentChannel` contract ABI bindings (ADR 003 § Payment Model).
//!
//! Generated by the `alloy::sol!` macro from the Solidity surface in
//! `contracts/src/PaymentChannel.sol`. Only the surface the node runtime's
//! seller-side settlement path consumes (#327) is mirrored:
//!
//! - reads: `usdc()` (the immutable settlement token, used to fill
//!   [`crate::channel::ChannelState::token`] since `ChannelOpened` does not
//!   carry it) and `getChannel(channelId)` (to read the on-chain
//!   `withdrawnAmount` watermark when deciding whether a redemption delta
//!   crosses the threshold);
//! - writes: `withdraw` (redeem accrued earnings while the channel stays
//!   open — no dispute window), `closeChannel` (initiate close with the
//!   latest voucher), and `settleChannel` (finalize after the window);
//! - events: `ChannelOpened` (provider learns of a channel opened against
//!   it → persist), `ChannelCloseInitiated` (observed-only here; the dispute
//!   monitor is deferred per #324), and `ChannelSettled` (→ forget the
//!   persisted channel state).
//!
//! The voucher EIP-712 domain (name `"PaymentChannel"`, version `"1"`) and
//! the `Voucher` type hash live in [`crate::voucher`]; the close/withdraw
//! `signature` argument is the bytes of a [`crate::voucher::SignedVoucher`]
//! over that domain. `disputeChannel` / `reclaimExpired` / `topUp` are
//! intentionally omitted (out of scope for the seller settlement path).

// The `sol!`-generated bindings include macro-emitted code that uses
// patterns workspace clippy denies (raw indexing into ABI fixed-size byte
// arrays, `unwrap` on infallible conversions). These allows scope the
// relaxation to this module only — same posture as `capacity_bond`.
#[allow(
    clippy::expect_used,
    clippy::indexing_slicing,
    clippy::panic,
    clippy::unwrap_used,
    clippy::pub_underscore_fields,
    clippy::missing_docs_in_private_items,
    clippy::too_many_arguments,
    missing_debug_implementations,
    missing_docs,
    non_snake_case,
    non_camel_case_types
)]
mod sol_types {
    alloy::sol! {
        #[sol(rpc)]
        contract PaymentChannel {
            // -----------------------------------------------------------------
            // Types — field order is part of the ABI; do not rearrange.
            // -----------------------------------------------------------------

            /// Channel lifecycle status. Mirrors the on-chain enum at
            /// `contracts/src/PaymentChannel.sol`.
            enum Status {
                Open,
                Closing,
                Closed
            }

            /// Per-channel on-chain state. Mirrors the on-chain `Channel`
            /// struct verbatim (including the packed trailing fields).
            struct Channel {
                address client;
                address provider;
                address token;
                uint256 deposit;
                uint256 claimedAmount;
                uint256 claimedNonce;
                uint256 claimedBytes;
                uint256 withdrawnAmount;
                uint256 withdrawnBytes;
                uint64 openedAt;
                uint64 expiresAt;
                uint64 disputeDeadline;
                Status status;
                bool extended;
            }

            // -----------------------------------------------------------------
            // View functions
            // -----------------------------------------------------------------

            /// Immutable settlement token (USDC). `ChannelOpened` omits the
            /// token, so the watcher reads this once at bootstrap to fill
            /// `ChannelState.token`; also doubles as the startup self-check
            /// view (a cheap call that confirms the configured address hosts
            /// the contract).
            function usdc() external view returns (address);

            /// Full on-chain channel record. The seller path reads
            /// `withdrawnAmount` to compute the un-redeemed delta.
            function getChannel(bytes32 channelId) external view returns (Channel memory);

            // -----------------------------------------------------------------
            // Write functions (provider/seller path)
            // -----------------------------------------------------------------

            /// Redeem accrued earnings against the latest client-signed
            /// voucher while the channel stays open. Monotonic client-signed
            /// claim → no dispute window. Routes the delta through `FeeRouter`
            /// same-tx. Caller MUST be `channel.provider`.
            function withdraw(
                bytes32 channelId,
                uint256 amount,
                uint256 nonce,
                uint256 bytesDelivered,
                bytes calldata signature
            ) external;

            /// Initiate channel close with the latest voucher; starts the
            /// dispute window. Callable by client or provider.
            function closeChannel(
                bytes32 channelId,
                uint256 amount,
                uint256 nonce,
                uint256 bytesDelivered,
                bytes calldata signature
            ) external;

            /// Finalize after the dispute window expires; routes the
            /// un-withdrawn remainder through `FeeRouter` and refunds the
            /// client. Callable by anyone.
            function settleChannel(bytes32 channelId) external;

            // -----------------------------------------------------------------
            // Events consumed by the seller settlement path
            // -----------------------------------------------------------------

            /// A client opened a channel. The watcher filters on the
            /// `provider` topic == self and persists a fresh `ChannelState`.
            event ChannelOpened(
                bytes32 indexed channelId,
                address indexed client,
                address indexed provider,
                uint256 deposit,
                uint256 expiresAt
            );

            /// Close initiated (dispute window open). Observed-only here —
            /// the in-process dispute monitor is deferred (#324).
            event ChannelCloseInitiated(
                bytes32 indexed channelId,
                address indexed initiator,
                uint256 amount,
                uint256 nonce,
                uint256 bytesDelivered,
                uint256 disputeDeadline
            );

            /// Channel settled and closed. The watcher drops the persisted
            /// `ChannelState` via `ChannelStateStore::forget`.
            event ChannelSettled(
                bytes32 indexed channelId,
                address indexed provider,
                uint256 routedAmount,
                uint256 bytesDelivered,
                uint256 clientRefund
            );
        }
    }
}

pub use sol_types::PaymentChannel;
