//! `PaymentChannel` contract ABI bindings (ADR 003 § Payment Model).
//!
//! Generated by the `alloy::sol!` macro from the Solidity surface in
//! `contracts/src/PaymentChannel.sol`. Mirrors the surface both the
//! seller-side settlement path (#327) and the buyer-side cache-miss path
//! (#744) consume:
//!
//! - reads: `usdc()` (the immutable settlement token, used to fill
//!   [`crate::channel::ChannelState::token`] since `ChannelOpened` does not
//!   carry it) and `getChannel(channelId)` (to read the on-chain
//!   `withdrawnAmount` watermark when deciding whether a redemption delta
//!   crosses the threshold);
//! - seller writes: `withdraw` (redeem accrued earnings while the channel
//!   stays open — no dispute window), `withdrawMany` (batch N single-channel
//!   redemptions into one tx with a single aggregated `FeeRouter` route — the
//!   redeem sweep's per-tick collapse, #1587), `closeChannel` (initiate close
//!   with the latest voucher), and `settleChannel` (finalize after the window);
//! - buyer writes (#744): `openChannel` (open a channel against an upstream
//!   provider on first cache-miss pull), `topUp` (extend an existing
//!   channel's deposit), and `reclaimExpired` (recover the deposit of an
//!   abandoned channel after expiry);
//! - events: `ChannelOpened` (the seller filters on `provider == self` to
//!   persist; the buyer decodes it from its own `openChannel` tx receipt to
//!   learn the `channelId` + `expiresAt`), `ChannelToppedUp`
//!   (→ raise the tracked deposit
//!   so post-top-up vouchers are not wrongly rejected),
//!   `ChannelCloseInitiated` (observed-only here; the dispute monitor is
//!   deferred per #324), `ChannelSettled` (→ forget the persisted channel
//!   state), and `ChannelExpiredReclaimed` (emitted by `reclaimExpired`; the
//!   buyer drops its record after its own reclaim tx, not by watching the log).
//!
//! The voucher EIP-712 domain (name `"PaymentChannel"`, version `"1"`) and
//! the `Voucher` type hash live in [`crate::voucher`]; the close/withdraw
//! `signature` argument is the bytes of a [`crate::voucher::SignedVoucher`]
//! over that domain. `disputeChannel` is intentionally omitted (the dispute
//! monitor is out of scope, #324).

// The `sol!`-generated bindings include macro-emitted code that uses
// patterns workspace clippy denies (raw indexing into ABI fixed-size byte
// arrays, `unwrap` on infallible conversions). These allows scope the
// relaxation to this module only — same posture as `capacity_bond`.
#[allow(
    clippy::expect_used,
    clippy::indexing_slicing,
    clippy::panic,
    clippy::unwrap_used,
    clippy::pub_underscore_fields,
    clippy::missing_docs_in_private_items,
    clippy::too_many_arguments,
    missing_debug_implementations,
    missing_docs,
    non_snake_case,
    non_camel_case_types
)]
mod sol_types {
    alloy::sol! {
        #[sol(rpc)]
        contract PaymentChannel {
            // -----------------------------------------------------------------
            // Types — field order is part of the ABI; do not rearrange.
            // -----------------------------------------------------------------

            /// Channel lifecycle status. Mirrors the on-chain enum at
            /// `contracts/src/PaymentChannel.sol`.
            enum Status {
                Open,
                Closing,
                Closed
            }

            /// Per-channel on-chain state. Mirrors the on-chain `Channel`
            /// struct verbatim — including field order, which packs each
            /// `address` with a `uint64` timestamp (and `status`) into shared
            /// slots. Field order is part of the `getChannel` ABI tuple.
            struct Channel {
                address client;
                uint64 openedAt;
                Status status;
                /// Address whose EIP-712 signature authorizes vouchers on this
                /// channel. Pinned at `openChannel`, never mutable, and the
                /// recovery target at every settlement path. Distinct from
                /// `client` (the funder / refund destination).
                address voucherSigner;
                address provider;
                uint64 expiresAt;
                address token;
                uint64 disputeDeadline;
                uint256 deposit;
                uint256 claimedAmount;
                uint256 claimedNonce;
                uint256 claimedBytes;
                uint256 withdrawnAmount;
                uint256 withdrawnBytes;
            }

            /// One leg of a batched `withdrawMany` redemption — the same
            /// `(channelId, amount, nonce, bytesDelivered, signature)` tuple a
            /// single `withdraw` takes. Field order is part of the ABI tuple; do
            /// not rearrange.
            struct WithdrawArgs {
                bytes32 channelId;
                uint256 amount;
                uint256 nonce;
                uint256 bytesDelivered;
                bytes signature;
            }

            // -----------------------------------------------------------------
            // View functions
            // -----------------------------------------------------------------

            /// Immutable settlement token (USDC). `ChannelOpened` omits the
            /// token, so the watcher reads this once at bootstrap to fill
            /// `ChannelState.token`; also doubles as the startup self-check
            /// view (a cheap call that confirms the configured address hosts
            /// the contract).
            function usdc() external view returns (address);

            /// Full on-chain channel record. The seller path reads
            /// `withdrawnAmount` to compute the un-redeemed delta.
            function getChannel(bytes32 channelId) external view returns (Channel memory);

            /// Governable per-megabyte delivery-rate floor (ADR 019 §3.1 /
            /// ADR 003) — the settlement-enforced minimum rate a voucher may
            /// pay per MB. The node reads it at startup and on every
            /// `RateBoundsUpdated` to clamp its advertised `rate_per_mb`. There
            /// is no governance ceiling; the wire constant `MAX_RATE_PER_MB` is
            /// the absolute upper bound.
            function getRateBounds() external view returns (uint256 floor);

            /// Per-client channel counter (public mapping getter). The *next*
            /// nonce `openChannel` will assign to `client`; the resulting
            /// `channelId` is `keccak256(client, provider, nonce)`. Reads let a
            /// caller derive a channel id without parsing the `ChannelOpened`
            /// receipt.
            function clientChannelNonce(address client) external view returns (uint256);

            /// How many channels have ever been opened against `provider`.
            function providerChannelCount(address provider) external view returns (uint256);

            /// A page of the channel ids opened against `provider`, oldest first.
            /// Append-only and never rewritten, so a settled or closed channel
            /// keeps its id and the ordering is stable — no pinned-block read is
            /// required. Resolve current state per id with `getChannel`.
            function providerChannels(address provider, uint256 offset, uint256 limit)
                external
                view
                returns (bytes32[] memory);

            /// A page of the channel ids `client` opened, oldest first.
            /// `clientChannelNonce(client)` is the count — the contract stores
            /// only the counterparty per nonce and recomputes each id, so there
            /// is no separate counter that could drift from the nonce.
            function clientChannels(address client, uint256 offset, uint256 limit)
                external
                view
                returns (bytes32[] memory);

            // -----------------------------------------------------------------
            // Write functions (provider/seller path)
            // -----------------------------------------------------------------

            /// Redeem accrued earnings against the latest client-signed
            /// voucher while the channel stays open. Monotonic client-signed
            /// claim → no dispute window. Routes the delta through `FeeRouter`
            /// same-tx. Caller MUST be `channel.provider`.
            function withdraw(
                bytes32 channelId,
                uint256 amount,
                uint256 nonce,
                uint256 bytesDelivered,
                bytes calldata signature
            ) external;

            /// Redeem many channels' accrued deltas in one transaction, routing
            /// the summed delta through `FeeRouter` a single time (#1587). Each
            /// leg is verified and its watermark advanced exactly as a standalone
            /// `withdraw`, but the gas-dominant three-bucket router split runs
            /// once over the aggregate — economically identical to N single
            /// `withdraw`s (same operator per leg, split linear in amount).
            /// Reverts if the summed routable delta is zero. Caller MUST be the
            /// `provider` of every leg's channel. The node's redeem sweep uses
            /// this to collapse a tick's N redemptions into one tx.
            function withdrawMany(WithdrawArgs[] calldata args) external;

            /// Initiate channel close with the latest voucher; starts the
            /// dispute window. Callable by client or provider.
            function closeChannel(
                bytes32 channelId,
                uint256 amount,
                uint256 nonce,
                uint256 bytesDelivered,
                bytes calldata signature
            ) external;

            /// Initiate close without presenting a voucher — the claim stays at
            /// whatever is already recorded on-chain — and start the dispute
            /// window, during which the counterparty can still dispute in a
            /// higher voucher. Callable by client or provider. This is the
            /// escape hatch for a party holding no voucher at all (e.g. a funder
            /// whose pinned `voucherSigner` never signed one). The node's own
            /// close paths (seller `send_close`, buyer `close_unilateral`) never
            /// reach it — both are guarded on holding a voucher — so the callers
            /// are the CLI `decdn channel close`/`clean` on a never-drawn
            /// channel, and tests opening a dispute window without one.
            function closeChannelWithoutVoucher(bytes32 channelId) external;

            /// Finalize after the dispute window expires; routes the
            /// un-withdrawn remainder through `FeeRouter` and refunds the
            /// client. Callable by anyone.
            function settleChannel(bytes32 channelId) external;

            /// Settle in one tx with NO dispute window, given a client voucher
            /// and a matching provider `CooperativeClose` waiver over the same
            /// final tuple (ADR 003 §Cooperative close). Callable by client or
            /// provider. Open-only.
            ///
            /// NOTE: this selector ships with the companion
            /// `PaymentChannel.cooperativeClose` contract change — calling it
            /// against a deployment that predates that change reverts (no such
            /// function). Callers gate on a configured contract version / chain
            /// rather than assuming every deployment exposes it.
            function cooperativeClose(
                bytes32 channelId,
                uint256 amount,
                uint256 nonce,
                uint256 bytesDelivered,
                bytes calldata clientVoucherSig,
                bytes calldata providerCloseSig
            ) external;

            // -----------------------------------------------------------------
            // Write functions (client/buyer path — #744)
            // -----------------------------------------------------------------

            /// Open a channel against `provider`, escrowing `deposit` USDC
            /// (pulled via `safeTransferFrom`, so the caller MUST have an
            /// allowance). Caller becomes `channel.client`. The buyer learns the
            /// `channelId` + `expiresAt` by decoding the `ChannelOpened` event
            /// from this tx's receipt (atomic with the open — no follow-up read).
            /// `voucherSigner` pins the address allowed to sign this channel's
            /// vouchers and is immutable thereafter; passing the zero address
            /// resolves it on-chain to the caller (the self-signing default).
            function openChannel(address provider, uint256 deposit, address voucherSigner)
                external
                returns (bytes32 channelId);

            /// Client-only: add `additionalDeposit` USDC to an open channel.
            /// Does not extend `expiresAt`.
            function topUp(bytes32 channelId, uint256 additionalDeposit) external;

            /// Refund the remaining deposit of an expired, never-closed
            /// channel to `channel.client`. Callable by client or provider;
            /// the refund always goes to the client (ADR 003 §reclaimExpired).
            function reclaimExpired(bytes32 channelId) external;

            // -----------------------------------------------------------------
            // Events consumed by the seller settlement path
            // -----------------------------------------------------------------

            /// A client opened a channel. The watcher filters on the
            /// `provider` topic == self and persists a fresh `ChannelState`.
            event ChannelOpened(
                bytes32 indexed channelId,
                address indexed client,
                address indexed provider,
                uint256 deposit,
                uint256 expiresAt,
                address voucherSigner
            );

            /// Client increased the channel deposit. The watcher updates the
            /// tracked `ChannelState.deposit` to `newDeposit` so the voucher
            /// handler's `amount <= deposit` check accepts post-top-up
            /// vouchers instead of rejecting them against the stale deposit.
            event ChannelToppedUp(
                bytes32 indexed channelId,
                uint256 additionalDeposit,
                uint256 newDeposit
            );

            /// Close initiated (dispute window open). Observed-only here —
            /// the in-process dispute monitor is deferred (#324).
            event ChannelCloseInitiated(
                bytes32 indexed channelId,
                address indexed initiator,
                uint256 amount,
                uint256 nonce,
                uint256 bytesDelivered,
                uint256 disputeDeadline
            );

            /// Channel settled and closed. The watcher drops the persisted
            /// `ChannelState` via `ChannelStateStore::forget`.
            event ChannelSettled(
                bytes32 indexed channelId,
                address indexed provider,
                uint256 routedAmount,
                uint256 bytesDelivered,
                uint256 clientRefund
            );

            /// Channel cooperatively closed and settled in one tx (no dispute
            /// window). The watcher drops the persisted `ChannelState` exactly
            /// as it does for `ChannelSettled` — `Closed` is terminal either way.
            /// Emitted only by deployments carrying the companion
            /// `cooperativeClose` contract change; older ones never emit it.
            event ChannelCooperativelyClosed(
                bytes32 indexed channelId,
                address indexed provider,
                uint256 routedAmount,
                uint256 bytesDelivered,
                uint256 clientRefund
            );

            /// Expired channel reclaimed: the remaining deposit was refunded
            /// to `client`. Emitted by `reclaimExpired`; the buyer drops its
            /// persisted buyer-channel record after its own `reclaimExpired`
            /// receipt succeeds — it does not watch this log (#744).
            event ChannelExpiredReclaimed(
                bytes32 indexed channelId,
                address indexed client,
                uint256 clientRefund
            );

            /// Governance changed the per-MB delivery-rate floor (ADR 019
            /// §3.1). The rate-bounds watcher decodes the new floor and stores
            /// it into the node's live clamp so a governance retune reaches
            /// running nodes without a restart. No `indexed` params — matches
            /// `setRateBounds`.
            event RateBoundsUpdated(uint256 newDeliveryFloor);
        }
    }
}

pub use sol_types::PaymentChannel;
