//! `PaymentPool` contract ABI bindings (ADR 003 § `PaymentPool`).
//!
//! Generated by the `alloy::sol!` macro from the Solidity surface in
//! `contracts/src/PaymentPool.sol`. One funded USDC pool backs payments from
//! many independent capped signers to many nodes: an owner opens a single
//! pool and pays every node from it, never opening a pool per node or per
//! client. Signers are authorized off-chain by an owner-signed capability,
//! capped by a spending limit and an expiry, and registered lazily on first
//! redemption into a two-dimensional sharded register keyed by
//! `(signer, provider)`.
//!
//! Surface consumed by both the seller-side settlement path (a node redeems
//! vouchers presented against its own `provider` address) and the buyer-side
//! cache-miss path (the node opens and tops up its own pool as a paying
//! client on the upstream leg):
//!
//! - reads: `usdc()` and `feeRouter()` (immutables/governable addresses),
//!   `getPool(poolId)` (owner, status, deposit, dispute deadline,
//!   totalRedeemed), `getAuthorization(poolId, signer)` (spending cap,
//!   expiry, spent), `getAuthorizations(poolIds, signers)` (the batch
//!   companion to `getAuthorization`, one read per pair in input order),
//!   `getWatermark(poolId, signer, provider)` (the
//!   cumulative-paid lane a redeemer advances), `ownerPoolNonce(owner)` (next
//!   nonce used to derive a pool id), `getPools(owner, offset, limit)` (page
//!   of an owner's pool ids), and `getRateBounds()` (the governable per-MB
//!   delivery-rate floor);
//! - owner writes: `openPool` (escrow a deposit and derive a fresh
//!   `poolId`), `topUp` (add funds to an open pool), `closePool` (start the
//!   grace-window close — `redeem` stays callable until the dispute
//!   deadline), and `reclaim` (callable by anyone once the window elapses;
//!   refunds the owner's residual and closes the pool);
//! - redeemer (node) writes: `redeem` (pay a single `(signer, provider)`
//!   lane against a monotone cumulative voucher, optionally registering the
//!   signer's capability in the same call) and `redeemMany` (register a
//!   batch of capabilities, then redeem a batch of vouchers, in one
//!   transaction — the node's redeem sweep collapses a tick's redemptions
//!   into one tx);
//! - events: `PoolOpened`, `PoolToppedUp` (→ raise the tracked deposit so
//!   post-top-up vouchers are not wrongly rejected), `PoolRedeemed` (a node
//!   filters on its own `provider` topic as the single write path for the
//!   paid side), `PoolCloseInitiated` (the owner started the grace-window
//!   close), `PoolReclaimed` (the residual was refunded and the pool is now
//!   closed), and `RateBoundsUpdated` (the rate-bounds watcher decodes the
//!   new floor and clamps the node's advertised `rate_per_mb`).
//!
//! The capability/voucher EIP-712 domain (name `"PaymentPool"`, version
//! `"1"`) lives in [`crate::voucher`]; the `capability` argument to `redeem`
//! is the ABI-encoded `(spendingCap, expiry, ownerSig)` tuple carrying the
//! owner's EIP-712 `Capability` signature, and `voucherSig` is the signer's
//! EIP-712 `Voucher` signature over `{poolId, signer, provider, cumulative,
//! bytesDelivered}`.

// The `sol!`-generated bindings include macro-emitted code that uses
// patterns workspace clippy denies (raw indexing into ABI fixed-size byte
// arrays, `unwrap` on infallible conversions). These allows scope the
// relaxation to this module only — same posture as `capacity_bond`.
#[allow(
    clippy::expect_used,
    clippy::indexing_slicing,
    clippy::panic,
    clippy::unwrap_used,
    clippy::pub_underscore_fields,
    clippy::missing_docs_in_private_items,
    clippy::too_many_arguments,
    missing_debug_implementations,
    missing_docs,
    non_snake_case,
    non_camel_case_types
)]
mod sol_types {
    alloy::sol! {
        #[sol(rpc)]
        contract PaymentPool {
            // -----------------------------------------------------------------
            // Types — field order is part of the ABI; do not rearrange.
            // -----------------------------------------------------------------

            /// Pool lifecycle status. Mirrors the on-chain enum at
            /// `contracts/src/PaymentPool.sol`.
            enum Status {
                Open,
                Closing,
                Closed
            }

            /// Per-pool on-chain state. Mirrors the on-chain `Pool` struct
            /// verbatim — including field order, which is part of the
            /// `getPool` ABI tuple.
            struct Pool {
                address owner;
                Status status;
                uint64 disputeDeadline;
                uint64 deposit;
                uint64 totalRedeemed;
            }

            /// Per-`(pool, signer)` authorization, set once on first
            /// redemption for that signer from the owner-signed capability.
            /// Field order is part of the `getAuthorization` ABI tuple.
            struct Authorization {
                uint64 cap;
                uint64 expiry;
                uint64 spent;
            }

            /// Per-`(pool, signer, provider)` redemption lane. Field order
            /// is part of the `getWatermark` ABI tuple.
            struct Lane {
                uint64 amount;
                uint64 bytesDelivered;
            }

            /// One signer registration inside a pool's batch: the owner's
            /// EIP-712 `Capability` signature and the limits it authorizes.
            /// The pool is the enclosing `PoolBatch`. Field order is part of
            /// the ABI tuple; do not rearrange.
            struct CapabilityReg {
                address signer;
                uint64 spendingCap;
                uint64 expiry;
                bytes ownerSig;
            }

            /// One lane's voucher inside a pool's batch. Names neither its
            /// pool (the enclosing `PoolBatch` does) nor its payee: the
            /// contract redeems for `msg.sender` and rebuilds the EIP-712
            /// hash with it, so a voucher signed for another node fails as
            /// `InvalidVoucherSignature`. The signature is the EIP-2098
            /// compact pair `(r, vs)`, which makes this struct *static*: an
            /// array of it carries no per-element offset, no length word and
            /// no padding. A voucher signer must therefore be an EOA — the
            /// contract recovers with `ecrecover`, not ERC-1271. Field order
            /// is part of the ABI tuple; do not rearrange.
            ///
            /// The three chain words bring a lane to 8 words / 256 calldata
            /// bytes (ADR 003 §Voucher signatures are compact). `chainMeter`
            /// is the packing that keeps it at 8 rather than 9:
            ///
            /// ```text
            ///  byte  0                     22 23            30 31
            ///       +------------------------+----------------+--+
            ///       |  reserved — MUST be 0  |   chunkPrice   |ci|
            ///       +------------------------+----------------+--+
            /// ```
            ///
            /// The packing is invisible to signers: the contract decodes
            /// `chunkPrice`, widens it back to `uint256`, and rebuilds the
            /// same EIP-712 digest, while `chainIndex` is a redemption
            /// parameter and is not signed at all. On a cooperative
            /// redemption all three words are nearly all zero bytes — a
            /// closing voucher carries a zero root, a zero preimage, and a
            /// zero index — so they compress to almost nothing on an L2.
            struct LaneVoucher {
                address signer;
                uint64 cumulative;
                uint64 bytesDelivered;
                bytes32 r;
                bytes32 vs;
                bytes32 chainRoot;
                bytes32 preimage;
                uint256 chainMeter;
            }

            /// Everything a node redeems against one pool. Naming the pool
            /// once per group rather than once per entry is both the
            /// calldata saving and what lets the pool's status gate and its
            /// `totalRedeemed` write happen once for the whole group. Field
            /// order is part of the ABI tuple; do not rearrange.
            struct PoolBatch {
                bytes32 poolId;
                CapabilityReg[] capabilities;
                LaneVoucher[] vouchers;
            }

            // -----------------------------------------------------------------
            // View functions
            // -----------------------------------------------------------------

            /// Immutable settlement token (USDC).
            function usdc() external view returns (address);

            /// Governance-re-pointable settlement router target.
            function feeRouter() external view returns (address);

            /// Full on-chain pool record.
            function getPool(bytes32 poolId) external view returns (Pool memory);

            /// A signer's spending cap, expiry, and spent-so-far against a
            /// pool. Zero cap and zero expiry means the signer is not yet
            /// registered.
            function getAuthorization(bytes32 poolId, address signer) external view returns (Authorization memory);

            /// Batch companion to `getAuthorization`: one
            /// `authorized[poolId][signer]` read per `(poolIds[i],
            /// signers[i])` pair, in input order. Reverts on a length
            /// mismatch. The redeemer reads every lane whose registration it
            /// does not already know in one call instead of one `eth_call`
            /// per lane.
            function getAuthorizations(bytes32[] calldata poolIds, address[] calldata signers)
                external
                view
                returns (Authorization[] memory);

            /// A `(signer, provider)` lane's cumulative-paid amount and
            /// cumulative paid-proportional bytes delivered.
            function getWatermark(bytes32 poolId, address signer, address provider)
                external
                view
                returns (Lane memory);

            /// Governable per-megabyte delivery-rate floor (ADR 005 / ADR
            /// 003) — the settlement-enforced minimum rate a voucher may pay
            /// per MB. The node reads it at startup and on every
            /// `RateBoundsUpdated` to clamp its advertised `rate_per_mb`.
            function getRateBounds() external view returns (uint256 floor);

            /// Per-owner monotonic pool counter (public mapping getter). The
            /// *next* nonce `openPool` will assign to `owner`; the resulting
            /// `poolId` is `keccak256(owner, nonce)`.
            function ownerPoolNonce(address owner) external view returns (uint256);

            /// A page of the pool ids `owner` has opened, oldest first.
            /// `ownerPoolNonce(owner)` is the count.
            function getPools(address owner, uint256 offset, uint256 limit)
                external
                view
                returns (bytes32[] memory);

            // -----------------------------------------------------------------
            // Write functions (owner path)
            // -----------------------------------------------------------------

            /// Open a USDC pool; transfers `deposit` in and derives
            /// `poolId = keccak256(owner, ownerPoolNonce[owner])`. Names no
            /// provider and no signer — a pool is bound to no payee at open.
            function openPool(uint64 deposit) external returns (bytes32 poolId);

            /// Owner-only: add `additionalDeposit` USDC to an open pool.
            function topUp(bytes32 poolId, uint64 additionalDeposit) external;

            /// Owner-only: start the grace-window close on `poolId`. Moves
            /// no funds — redemption stays callable until `disputeDeadline`.
            function closePool(bytes32 poolId) external;

            /// Callable by anyone once the grace window has elapsed:
            /// transfers `deposit - totalRedeemed` to the owner and closes
            /// the pool.
            function reclaim(bytes32 poolId) external;

            // -----------------------------------------------------------------
            // Write functions (redeemer / node path)
            // -----------------------------------------------------------------

            /// The sole redemption entry point: per pool, register every
            /// capability, then redeem every voucher, all in one
            /// transaction. A node redeems every lane it holds at once, and
            /// a single lane is a one-pool batch of one. Each voucher pays
            /// the increment over its lane watermark, bounded by the
            /// signer's remaining cap and the pool's remaining deposit; a
            /// transient-empty voucher (already-registered signer, expired
            /// capability, stale cumulative, or a drained lane/cap) is
            /// skipped rather than reverting. Grouping by pool is what makes
            /// the pool's status gate and its `totalRedeemed` write happen
            /// once per group instead of once per lane. Every voucher is
            /// redeemed for `msg.sender`, so the whole call's payout settles
            /// through `FeeRouter.routeSettlement` in one go.
            function redeemMany(PoolBatch[] calldata batches) external returns (uint256 totalPaid);

            // -----------------------------------------------------------------
            // Events
            // -----------------------------------------------------------------

            /// An owner opened a pool.
            event PoolOpened(bytes32 indexed poolId, address indexed owner, uint256 deposit);

            /// An owner topped up an open pool. The watcher updates the
            /// tracked deposit to `newDeposit` so a redeemer's `paid <=
            /// remaining deposit` bound accepts post-top-up redemptions
            /// instead of rejecting them against a stale deposit.
            event PoolToppedUp(bytes32 indexed poolId, uint256 additionalDeposit, uint256 newDeposit);

            /// One lane's outcome inside a `PoolRedeemed`.
            /// `newPaidCumulative` is the lane's cumulative paid amount
            /// after the advance — the value a node writes to its paid
            /// watermark, cumulative rather than a delta so the stream is
            /// idempotent and survives a gap. `bytesPaid` is the
            /// paid-proportional served byte count, carried for per-lane
            /// accounting. Field order is part of the ABI tuple; do not
            /// rearrange.
            struct LaneSettled {
                address signer;
                uint64 newPaidCumulative;
                uint64 bytesPaid;
            }

            /// A node cashed vouchers against one pool: one event per pool
            /// group, with an entry per lane that actually paid. Emitting
            /// once for the group rather than once per lane is what keeps
            /// the log base and its topics off the per-lane cost. A node
            /// follows this event, filtered on its own `provider`, as the
            /// single write path for the paid side.
            event PoolRedeemed(bytes32 indexed poolId, address indexed provider, LaneSettled[] lanes);

            /// The owner started the grace-window close on `poolId`.
            /// `redeem` stays callable until `disputeDeadline`.
            event PoolCloseInitiated(bytes32 indexed poolId, address indexed owner, uint256 disputeDeadline);

            /// `reclaim` refunded `ownerRefund` (`deposit - totalRedeemed`)
            /// to `owner` and the pool is now `Closed`.
            event PoolReclaimed(bytes32 indexed poolId, address indexed owner, uint256 ownerRefund);

            /// Governance changed the per-MB delivery-rate floor. The
            /// rate-bounds watcher decodes the new floor and stores it into
            /// the node's live clamp so a governance retune reaches running
            /// nodes without a restart. No `indexed` params — matches
            /// `setRateBounds`.
            event RateBoundsUpdated(uint256 newDeliveryFloor);
        }
    }

    alloy::sol! {
        #[sol(rpc)]
        contract FeeRouter {
            /// Current fee split, as `[operator, buyback, treasury]` basis
            /// points summing to `BPS_DENOMINATOR`. Mirrors
            /// `contracts/src/FeeRouter.sol`.
            function getShares() external view returns (uint256[3]);

            /// Governance retuned the fee split. The fee-shares watcher
            /// decodes the new split and stores the operator bucket into the
            /// node's live cell so a governance retune reaches running nodes
            /// without a restart.
            event SharesUpdated(uint256[3] newShares);
        }
    }
}

pub use sol_types::{FeeRouter, PaymentPool};

/// Narrow a USDC amount, or a byte count, to the `uint64` the `PaymentPool`
/// carries in its packed fields.
///
/// Off-chain the amounts travel as `U256`, because that is the width the ERC-20
/// surface and the voucher store speak. On-chain every USDC counter and both
/// lane watermarks are `uint64`: at USDC's six decimals that ceiling is about
/// $18.4 trillion, and 18.4 exabytes for a byte count, so this rejects only a
/// value that could never have been a real lane. Call it at the contract
/// boundary rather than widening the callers.
///
/// # Errors
///
/// Errors if `value` does not fit `u64`, naming `what` so the caller's context
/// says which field overflowed.
pub fn to_pool_u64(value: alloy::primitives::U256, what: &str) -> anyhow::Result<u64> {
    u64::try_from(value)
        .map_err(|_| anyhow::anyhow!("{what} {value} exceeds the PaymentPool's uint64 field"))
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::indexing_slicing)]
mod tests {
    use alloy::primitives::{Address, B256, U256};
    use alloy::sol_types::SolEvent;

    use super::{PaymentPool, to_pool_u64};

    /// Pins the `PoolRedeemed` event signature (and therefore its topic-0
    /// selector) to `contracts/src/PaymentPool.sol`'s field list, so a drift
    /// between the Solidity source and this binding fails the build instead
    /// of silently mis-decoding a node's settlement log.
    ///
    /// The ABI signature string does not encode which params are `indexed`
    /// — see `pool_redeemed_indexed_layout_matches_contract` below for the
    /// companion pin on topic/data placement.
    #[test]
    fn pool_redeemed_signature_matches_contract() {
        assert_eq!(
            PaymentPool::PoolRedeemed::SIGNATURE,
            "PoolRedeemed(bytes32,address,(address,uint64,uint64)[])"
        );
    }

    /// Pins which `PoolRedeemed` params are `indexed`: `poolId` and
    /// `provider` land in the log's topics (topic0 is the selector, topics
    /// 1-2 the indexed params); the `lanes` array lands in the log data,
    /// carrying `signer` per entry rather than as a topic. The
    /// signature-string pin above is blind to this split, so a future edit
    /// that moved `indexed` onto the wrong param would pass that test while
    /// silently breaking a node's `provider`-topic filter for its settlement
    /// watcher. This test builds the event with distinct sentinel values and
    /// checks each one landed where the ABI encoding puts it.
    #[test]
    fn pool_redeemed_indexed_layout_matches_contract() {
        let pool_id = B256::repeat_byte(0x11);
        let provider = Address::repeat_byte(0x33);
        let signer_a = Address::repeat_byte(0x22);
        let signer_b = Address::repeat_byte(0x44);

        let event = PaymentPool::PoolRedeemed {
            poolId: pool_id,
            provider,
            lanes: vec![
                PaymentPool::LaneSettled {
                    signer: signer_a,
                    newPaidCumulative: 3_000,
                    bytesPaid: 2_000,
                },
                PaymentPool::LaneSettled {
                    signer: signer_b,
                    newPaidCumulative: 7_000,
                    bytesPaid: 5_000,
                },
            ],
        };
        let log = event.encode_log_data();

        // topic0 (selector) + exactly the 2 indexed params. `signer` is per
        // lane now, so it cannot be a topic — a node keys the lane from the
        // decoded entry instead.
        assert_eq!(log.topics().len(), 3);
        assert_eq!(
            log.topics().first(),
            Some(&PaymentPool::PoolRedeemed::SIGNATURE_HASH)
        );
        assert_eq!(log.topics().get(1), Some(&pool_id));
        assert_eq!(log.topics().get(2), Some(&provider.into_word()));

        // The dynamic array is head-encoded (offset, then length, then the
        // static entries), so the whole payload is 2 framing words plus 3
        // words per lane — which is the shape the per-lane log cost rests on.
        assert_eq!(log.data.len(), 32 * (2 + 3 * 2));

        // Round-trip through the decoder recovers the same lanes, proving the
        // topic/data split above is exactly what a real watcher decodes.
        let decoded = PaymentPool::PoolRedeemed::decode_log_data(&log).unwrap();
        assert_eq!(decoded.poolId, pool_id);
        assert_eq!(decoded.provider, provider);
        assert_eq!(decoded.lanes.len(), 2);
        assert_eq!(decoded.lanes[0].signer, signer_a);
        assert_eq!(decoded.lanes[0].newPaidCumulative, 3_000);
        assert_eq!(decoded.lanes[0].bytesPaid, 2_000);
        assert_eq!(decoded.lanes[1].signer, signer_b);
        assert_eq!(decoded.lanes[1].newPaidCumulative, 7_000);
    }

    /// The narrowing guard on the money path: every USDC amount crosses into
    /// the contract through here, so the ceiling is worth pinning at the exact
    /// boundary rather than trusting the `try_from`. `u64::MAX` is a legal
    /// deposit (~$18.4 trillion at six decimals); one base unit more is not
    /// expressible on-chain and must be refused rather than truncated — a
    /// silent wrap here would understate a pool's deposit.
    #[test]
    fn to_pool_u64_accepts_the_ceiling_and_refuses_one_past_it() -> anyhow::Result<()> {
        let ceiling = U256::from(u64::MAX);
        assert_eq!(to_pool_u64(ceiling, "deposit")?, u64::MAX);

        let over = ceiling + U256::from(1u8);
        let Err(err) = to_pool_u64(over, "deposit") else {
            anyhow::bail!("one base unit past the ceiling must be refused, not truncated");
        };
        assert!(
            err.to_string().contains("deposit"),
            "the error names the field that overflowed, got: {err}"
        );
        Ok(())
    }

    /// Pins the field list of every struct the read surface decodes into, so
    /// a drift between `contracts/src/PaymentPool.sol` and this binding fails
    /// the build.
    ///
    /// The event pins above do not cover these: a `sol!` block is a *hand-written
    /// restatement* of the ABI, not something derived from the Solidity source,
    /// so a struct that gains, loses or narrows a field here compiles perfectly
    /// against a contract that disagrees. `getPool` then decodes a `Pool` whose
    /// fields have silently shifted, the node reads a garbage `owner`, and the
    /// only symptom is a node refusing to serve — no compile error, no decode
    /// error, nothing until an anvil run. Pinning the layout is what turns that
    /// into a build failure.
    ///
    /// `eip712_encode_type` is used purely as a stable printer for the field
    /// list; none of these structs is EIP-712 signed.
    #[test]
    fn read_surface_struct_layouts_match_contract() {
        use alloy::sol_types::SolStruct;

        assert_eq!(
            PaymentPool::Pool::eip712_encode_type(),
            "Pool(address owner,uint8 status,uint64 disputeDeadline,uint64 deposit,uint64 totalRedeemed)",
            "getPool"
        );
        assert_eq!(
            PaymentPool::Authorization::eip712_encode_type(),
            "Authorization(uint64 cap,uint64 expiry,uint64 spent)",
            "getAuthorization"
        );
        assert_eq!(
            PaymentPool::Lane::eip712_encode_type(),
            "Lane(uint64 amount,uint64 bytesDelivered)",
            "getWatermark"
        );
    }

    /// The same pin for the two structs `redeemMany` takes as calldata. A
    /// silent drift here would encode a batch the contract cannot decode.
    #[test]
    fn redeem_call_struct_layouts_match_contract() {
        use alloy::sol_types::SolStruct;

        assert_eq!(
            PaymentPool::CapabilityReg::eip712_encode_type(),
            "CapabilityReg(address signer,uint64 spendingCap,uint64 expiry,bytes ownerSig)"
        );
        assert_eq!(
            PaymentPool::LaneVoucher::eip712_encode_type(),
            "LaneVoucher(address signer,uint64 cumulative,uint64 bytesDelivered,bytes32 r,bytes32 vs,bytes32 chainRoot,bytes32 preimage,uint256 chainMeter)"
        );
    }

    /// Same pin for the other four ABI-tuple-carrying events consumed by
    /// the node's watchers.
    #[test]
    fn lifecycle_event_signatures_match_contract() {
        assert_eq!(
            PaymentPool::PoolOpened::SIGNATURE,
            "PoolOpened(bytes32,address,uint256)"
        );
        assert_eq!(
            PaymentPool::PoolToppedUp::SIGNATURE,
            "PoolToppedUp(bytes32,uint256,uint256)"
        );
        assert_eq!(
            PaymentPool::PoolCloseInitiated::SIGNATURE,
            "PoolCloseInitiated(bytes32,address,uint256)"
        );
        assert_eq!(
            PaymentPool::PoolReclaimed::SIGNATURE,
            "PoolReclaimed(bytes32,address,uint256)"
        );
        assert_eq!(
            PaymentPool::RateBoundsUpdated::SIGNATURE,
            "RateBoundsUpdated(uint256)"
        );
    }

    /// Batch companion selector for `getAuthorization` (ADR 003 § redeemer
    /// batching).
    #[test]
    fn get_authorizations_signature_matches_contract() {
        use alloy::sol_types::SolCall;
        assert_eq!(
            PaymentPool::getAuthorizationsCall::SIGNATURE,
            "getAuthorizations(bytes32[],address[])"
        );
    }
}
