//! `PaymentChannel` contract ABI bindings (ADR 003 § Payment Model).
//!
//! Generated by the `alloy::sol!` macro from the Solidity surface in
//! `contracts/src/PaymentChannel.sol`. Mirrors the surface both the
//! seller-side settlement path (#327) and the buyer-side cache-miss path
//! (#744) consume:
//!
//! - reads: `usdc()` (the immutable settlement token, used to fill
//!   [`crate::channel::ChannelState::token`] since `ChannelOpened` does not
//!   carry it) and `getChannel(channelId)` (to read the on-chain
//!   `withdrawnAmount` watermark when deciding whether a redemption delta
//!   crosses the threshold), plus `minDeposit()` (the buyer-path deposit
//!   floor);
//! - seller writes: `withdraw` (redeem accrued earnings while the channel
//!   stays open — no dispute window), `closeChannel` (initiate close with the
//!   latest voucher), and `settleChannel` (finalize after the window);
//! - buyer writes (#744): `openChannel` (open a channel against an upstream
//!   provider on first cache-miss pull), `topUp` (extend an existing
//!   channel's deposit), and `reclaimExpired` (recover the deposit of an
//!   abandoned channel after expiry);
//! - events: `ChannelOpened` (the seller filters on `provider == self` to
//!   persist; the buyer decodes it from its own `openChannel` tx receipt to
//!   learn the `channelId` + `expiresAt`), `ChannelToppedUp`
//!   (→ raise the tracked deposit
//!   so post-top-up vouchers are not wrongly rejected),
//!   `ChannelCloseInitiated` (observed-only here; the dispute monitor is
//!   deferred per #324), `ChannelSettled` (→ forget the persisted channel
//!   state), and `ChannelExpiredReclaimed` (emitted by `reclaimExpired`; the
//!   buyer drops its record after its own reclaim tx, not by watching the log).
//!
//! The voucher EIP-712 domain (name `"PaymentChannel"`, version `"1"`) and
//! the `Voucher` type hash live in [`crate::voucher`]; the close/withdraw
//! `signature` argument is the bytes of a [`crate::voucher::SignedVoucher`]
//! over that domain. `disputeChannel` is intentionally omitted (the dispute
//! monitor is out of scope, #324).

// The `sol!`-generated bindings include macro-emitted code that uses
// patterns workspace clippy denies (raw indexing into ABI fixed-size byte
// arrays, `unwrap` on infallible conversions). These allows scope the
// relaxation to this module only — same posture as `capacity_bond`.
#[allow(
    clippy::expect_used,
    clippy::indexing_slicing,
    clippy::panic,
    clippy::unwrap_used,
    clippy::pub_underscore_fields,
    clippy::missing_docs_in_private_items,
    clippy::too_many_arguments,
    missing_debug_implementations,
    missing_docs,
    non_snake_case,
    non_camel_case_types
)]
mod sol_types {
    alloy::sol! {
        #[sol(rpc)]
        contract PaymentChannel {
            // -----------------------------------------------------------------
            // Types — field order is part of the ABI; do not rearrange.
            // -----------------------------------------------------------------

            /// Channel lifecycle status. Mirrors the on-chain enum at
            /// `contracts/src/PaymentChannel.sol`.
            enum Status {
                Open,
                Closing,
                Closed
            }

            /// Per-channel on-chain state. Mirrors the on-chain `Channel`
            /// struct verbatim (including the packed trailing fields).
            struct Channel {
                address client;
                address provider;
                address token;
                uint256 deposit;
                uint256 claimedAmount;
                uint256 claimedNonce;
                uint256 claimedBytes;
                uint256 withdrawnAmount;
                uint256 withdrawnBytes;
                uint64 openedAt;
                uint64 expiresAt;
                uint64 disputeDeadline;
                Status status;
                bool extended;
            }

            // -----------------------------------------------------------------
            // View functions
            // -----------------------------------------------------------------

            /// Immutable settlement token (USDC). `ChannelOpened` omits the
            /// token, so the watcher reads this once at bootstrap to fill
            /// `ChannelState.token`; also doubles as the startup self-check
            /// view (a cheap call that confirms the configured address hosts
            /// the contract).
            function usdc() external view returns (address);

            /// Full on-chain channel record. The seller path reads
            /// `withdrawnAmount` to compute the un-redeemed delta.
            function getChannel(bytes32 channelId) external view returns (Channel memory);

            /// Governable minimum deposit (token base units) enforced by
            /// `openChannel`. The buyer path reads it to clamp a configured
            /// deposit up to the on-chain floor before opening.
            function minDeposit() external view returns (uint256);

            /// Per-client channel counter (public mapping getter). The *next*
            /// nonce `openChannel` will assign to `client`; the resulting
            /// `channelId` is `keccak256(client, provider, nonce)`. Reads let a
            /// caller derive a channel id without parsing the `ChannelOpened`
            /// receipt.
            function clientChannelNonce(address client) external view returns (uint256);

            // -----------------------------------------------------------------
            // Write functions (provider/seller path)
            // -----------------------------------------------------------------

            /// Redeem accrued earnings against the latest client-signed
            /// voucher while the channel stays open. Monotonic client-signed
            /// claim → no dispute window. Routes the delta through `FeeRouter`
            /// same-tx. Caller MUST be `channel.provider`.
            function withdraw(
                bytes32 channelId,
                uint256 amount,
                uint256 nonce,
                uint256 bytesDelivered,
                bytes calldata signature
            ) external;

            /// Initiate channel close with the latest voucher; starts the
            /// dispute window. Callable by client or provider.
            function closeChannel(
                bytes32 channelId,
                uint256 amount,
                uint256 nonce,
                uint256 bytesDelivered,
                bytes calldata signature
            ) external;

            /// Finalize after the dispute window expires; routes the
            /// un-withdrawn remainder through `FeeRouter` and refunds the
            /// client. Callable by anyone.
            function settleChannel(bytes32 channelId) external;

            /// Settle in one tx with NO dispute window, given a client voucher
            /// and a matching provider `CooperativeClose` waiver over the same
            /// final tuple (ADR 003 §Cooperative close). Callable by client or
            /// provider. Open-only.
            function cooperativeClose(
                bytes32 channelId,
                uint256 amount,
                uint256 nonce,
                uint256 bytesDelivered,
                bytes calldata clientVoucherSig,
                bytes calldata providerCloseSig
            ) external;

            // -----------------------------------------------------------------
            // Write functions (client/buyer path — #744)
            // -----------------------------------------------------------------

            /// Open a channel against `provider`, escrowing `deposit` USDC
            /// (pulled via `safeTransferFrom`, so the caller MUST have an
            /// allowance). Caller becomes `channel.client`. The buyer learns the
            /// `channelId` + `expiresAt` by decoding the `ChannelOpened` event
            /// from this tx's receipt (atomic with the open — no follow-up read).
            function openChannel(address provider, uint256 deposit) external returns (bytes32 channelId);

            /// Client-only: add `additionalDeposit` USDC to an open channel.
            /// Does not extend `expiresAt`.
            function topUp(bytes32 channelId, uint256 additionalDeposit) external;

            /// Refund the remaining deposit of an expired, never-closed
            /// channel to `channel.client`. Callable by client or provider;
            /// the refund always goes to the client (ADR 003 §reclaimExpired).
            function reclaimExpired(bytes32 channelId) external;

            // -----------------------------------------------------------------
            // Events consumed by the seller settlement path
            // -----------------------------------------------------------------

            /// A client opened a channel. The watcher filters on the
            /// `provider` topic == self and persists a fresh `ChannelState`.
            event ChannelOpened(
                bytes32 indexed channelId,
                address indexed client,
                address indexed provider,
                uint256 deposit,
                uint256 expiresAt
            );

            /// Client increased the channel deposit. The watcher updates the
            /// tracked `ChannelState.deposit` to `newDeposit` so the voucher
            /// handler's `amount <= deposit` check accepts post-top-up
            /// vouchers instead of rejecting them against the stale deposit.
            event ChannelToppedUp(
                bytes32 indexed channelId,
                uint256 additionalDeposit,
                uint256 newDeposit
            );

            /// Close initiated (dispute window open). Observed-only here —
            /// the in-process dispute monitor is deferred (#324).
            event ChannelCloseInitiated(
                bytes32 indexed channelId,
                address indexed initiator,
                uint256 amount,
                uint256 nonce,
                uint256 bytesDelivered,
                uint256 disputeDeadline
            );

            /// Channel settled and closed. The watcher drops the persisted
            /// `ChannelState` via `ChannelStateStore::forget`.
            event ChannelSettled(
                bytes32 indexed channelId,
                address indexed provider,
                uint256 routedAmount,
                uint256 bytesDelivered,
                uint256 clientRefund
            );

            /// Channel cooperatively closed and settled in one tx (no dispute
            /// window). The watcher drops the persisted `ChannelState` exactly
            /// as it does for `ChannelSettled` — `Closed` is terminal either way.
            event ChannelCooperativelyClosed(
                bytes32 indexed channelId,
                address indexed provider,
                uint256 routedAmount,
                uint256 bytesDelivered,
                uint256 clientRefund
            );

            /// Expired channel reclaimed: the remaining deposit was refunded
            /// to `client`. Emitted by `reclaimExpired`; the buyer drops its
            /// persisted buyer-channel record after its own `reclaimExpired`
            /// receipt succeeds — it does not watch this log (#744).
            event ChannelExpiredReclaimed(
                bytes32 indexed channelId,
                address indexed client,
                uint256 clientRefund
            );
        }
    }
}

pub use sol_types::PaymentChannel;
