//! `PaymentPool` contract ABI bindings (ADR 003 § `PaymentPool`).
//!
//! Generated by the `alloy::sol!` macro from the Solidity surface in
//! `contracts/src/PaymentPool.sol`. One funded USDC pool backs payments from
//! many independent capped signers to many nodes: an owner opens a single
//! pool and pays every node from it, never opening a pool per node or per
//! client. Signers are authorized off-chain by an owner-signed capability,
//! capped by a spending limit and an expiry, and registered lazily on first
//! redemption into a two-dimensional sharded register keyed by
//! `(signer, provider)`.
//!
//! Surface consumed by both the seller-side settlement path (a node redeems
//! vouchers presented against its own `provider` address) and the buyer-side
//! cache-miss path (the node opens and tops up its own pool as a paying
//! client on the upstream leg):
//!
//! - reads: `usdc()` and `feeRouter()` (immutables/governable addresses),
//!   `getPool(poolId)` (owner, status, deposit, dispute deadline,
//!   totalRedeemed), `getAuthorization(poolId, signer)` (spending cap,
//!   expiry, spent), `getWatermark(poolId, signer, provider)` (the
//!   cumulative-paid lane a redeemer advances), `ownerPoolNonce(owner)` (next
//!   nonce used to derive a pool id), `getPools(owner, offset, limit)` (page
//!   of an owner's pool ids), and `getRateBounds()` (the governable per-MB
//!   delivery-rate floor);
//! - owner writes: `openPool` (escrow a deposit and derive a fresh
//!   `poolId`), `topUp` (add funds to an open pool), `closePool` (start the
//!   grace-window close — `redeem` stays callable until the dispute
//!   deadline), and `reclaim` (callable by anyone once the window elapses;
//!   refunds the owner's residual and closes the pool);
//! - redeemer (node) writes: `redeem` (pay a single `(signer, provider)`
//!   lane against a monotone cumulative voucher, optionally registering the
//!   signer's capability in the same call) and `redeemMany` (register a
//!   batch of capabilities, then redeem a batch of vouchers, in one
//!   transaction — the node's redeem sweep collapses a tick's redemptions
//!   into one tx);
//! - events: `PoolOpened`, `PoolToppedUp` (→ raise the tracked deposit so
//!   post-top-up vouchers are not wrongly rejected), `PoolRedeemed` (a node
//!   filters on its own `provider` topic as the single write path for the
//!   paid side), `PoolCloseInitiated` (the owner started the grace-window
//!   close), `PoolReclaimed` (the residual was refunded and the pool is now
//!   closed), and `RateBoundsUpdated` (the rate-bounds watcher decodes the
//!   new floor and clamps the node's advertised `rate_per_mb`).
//!
//! The capability/voucher EIP-712 domain (name `"PaymentPool"`, version
//! `"1"`) lives in [`crate::voucher`]; the `capability` argument to `redeem`
//! is the ABI-encoded `(spendingCap, expiry, ownerSig)` tuple carrying the
//! owner's EIP-712 `Capability` signature, and `voucherSig` is the signer's
//! EIP-712 `Voucher` signature over `{poolId, signer, provider, cumulative,
//! bytesDelivered}`.

// The `sol!`-generated bindings include macro-emitted code that uses
// patterns workspace clippy denies (raw indexing into ABI fixed-size byte
// arrays, `unwrap` on infallible conversions). These allows scope the
// relaxation to this module only — same posture as `capacity_bond`.
#[allow(
    clippy::expect_used,
    clippy::indexing_slicing,
    clippy::panic,
    clippy::unwrap_used,
    clippy::pub_underscore_fields,
    clippy::missing_docs_in_private_items,
    clippy::too_many_arguments,
    missing_debug_implementations,
    missing_docs,
    non_snake_case,
    non_camel_case_types
)]
mod sol_types {
    alloy::sol! {
        #[sol(rpc)]
        contract PaymentPool {
            // -----------------------------------------------------------------
            // Types — field order is part of the ABI; do not rearrange.
            // -----------------------------------------------------------------

            /// Pool lifecycle status. Mirrors the on-chain enum at
            /// `contracts/src/PaymentPool.sol`.
            enum Status {
                Open,
                Closing,
                Closed
            }

            /// Per-pool on-chain state. Mirrors the on-chain `Pool` struct
            /// verbatim — including field order, which is part of the
            /// `getPool` ABI tuple.
            struct Pool {
                address owner;
                uint64 openedAt;
                Status status;
                address token;
                uint64 disputeDeadline;
                uint256 deposit;
                uint256 totalRedeemed;
            }

            /// Per-`(pool, signer)` authorization, set once on first
            /// redemption for that signer from the owner-signed capability.
            /// Field order is part of the `getAuthorization` ABI tuple.
            struct Authorization {
                uint256 cap;
                uint64 expiry;
                uint256 spent;
            }

            /// Per-`(pool, signer, provider)` redemption lane. Field order
            /// is part of the `getWatermark` ABI tuple.
            struct Lane {
                uint256 amount;
                uint256 bytesDelivered;
            }

            /// One `capabilities` entry in a batched `redeemMany` call —
            /// mirrors `redeem`'s decoded `(spendingCap, expiry, ownerSig)`
            /// capability tuple plus the `poolId`/`signer` it names. Field
            /// order is part of the ABI tuple; do not rearrange.
            struct CapabilityReg {
                bytes32 poolId;
                address signer;
                uint256 spendingCap;
                uint64 expiry;
                bytes ownerSig;
            }

            /// One `vouchers` entry in a batched `redeemMany` call — mirrors
            /// `redeem`'s voucher parameters plus the `poolId` it names.
            /// Field order is part of the ABI tuple; do not rearrange.
            struct RedeemVoucher {
                bytes32 poolId;
                address signer;
                address provider;
                uint256 cumulative;
                uint256 bytesDelivered;
                bytes voucherSig;
            }

            // -----------------------------------------------------------------
            // View functions
            // -----------------------------------------------------------------

            /// Immutable settlement token (USDC).
            function usdc() external view returns (address);

            /// Governance-re-pointable settlement router target.
            function feeRouter() external view returns (address);

            /// Full on-chain pool record.
            function getPool(bytes32 poolId) external view returns (Pool memory);

            /// A signer's spending cap, expiry, and spent-so-far against a
            /// pool. Zero cap and zero expiry means the signer is not yet
            /// registered.
            function getAuthorization(bytes32 poolId, address signer) external view returns (Authorization memory);

            /// A `(signer, provider)` lane's cumulative-paid amount and
            /// cumulative paid-proportional bytes delivered.
            function getWatermark(bytes32 poolId, address signer, address provider)
                external
                view
                returns (Lane memory);

            /// Governable per-megabyte delivery-rate floor (ADR 005 / ADR
            /// 003) — the settlement-enforced minimum rate a voucher may pay
            /// per MB. The node reads it at startup and on every
            /// `RateBoundsUpdated` to clamp its advertised `rate_per_mb`.
            function getRateBounds() external view returns (uint256 floor);

            /// Per-owner monotonic pool counter (public mapping getter). The
            /// *next* nonce `openPool` will assign to `owner`; the resulting
            /// `poolId` is `keccak256(owner, nonce)`.
            function ownerPoolNonce(address owner) external view returns (uint256);

            /// A page of the pool ids `owner` has opened, oldest first.
            /// `ownerPoolNonce(owner)` is the count.
            function getPools(address owner, uint256 offset, uint256 limit)
                external
                view
                returns (bytes32[] memory);

            // -----------------------------------------------------------------
            // Write functions (owner path)
            // -----------------------------------------------------------------

            /// Open a USDC pool; transfers `deposit` in and derives
            /// `poolId = keccak256(owner, ownerPoolNonce[owner])`. Names no
            /// provider and no signer — a pool is bound to no payee at open.
            function openPool(uint256 deposit) external returns (bytes32 poolId);

            /// Owner-only: add `additionalDeposit` USDC to an open pool.
            function topUp(bytes32 poolId, uint256 additionalDeposit) external;

            /// Owner-only: start the grace-window close on `poolId`. Moves
            /// no funds — `redeem` stays callable until `disputeDeadline`.
            function closePool(bytes32 poolId) external;

            /// Callable by anyone once the grace window has elapsed:
            /// transfers `deposit - totalRedeemed` to the owner and closes
            /// the pool.
            function reclaim(bytes32 poolId) external;

            // -----------------------------------------------------------------
            // Write functions (redeemer / node path)
            // -----------------------------------------------------------------

            /// Pay a node against a monotone cumulative voucher while the
            /// pool is `Open` or inside the grace window. The payee
            /// (`provider == msg.sender`) presents the highest voucher it
            /// holds; redemption pays the increment over the lane
            /// watermark, bounded by the signer's remaining cap and the
            /// pool's remaining deposit, then routes the paid USDC through
            /// `FeeRouter.routeSettlement` in the same transaction.
            /// `capability` is the ABI-encoded `(spendingCap, expiry,
            /// ownerSig)` tuple on a signer's first redemption, or empty
            /// bytes for every later redemption of an already-registered
            /// signer.
            function redeem(
                bytes32 poolId,
                address signer,
                address provider,
                uint256 cumulative,
                uint256 bytesDelivered,
                bytes calldata voucherSig,
                bytes calldata capability
            ) external;

            /// Register every capability, then redeem every voucher, in one
            /// transaction. A node registers the signers it needs and
            /// redeems all its lanes at once; a transient-empty voucher
            /// (already-registered signer, expired capability, stale
            /// cumulative, or a drained lane/cap) is skipped rather than
            /// reverting the whole batch.
            function redeemMany(CapabilityReg[] calldata capabilities, RedeemVoucher[] calldata vouchers)
                external
                returns (uint256 totalPaid);

            // -----------------------------------------------------------------
            // Events
            // -----------------------------------------------------------------

            /// An owner opened a pool.
            event PoolOpened(bytes32 indexed poolId, address indexed owner, uint256 deposit);

            /// An owner topped up an open pool. The watcher updates the
            /// tracked deposit to `newDeposit` so a redeemer's `paid <=
            /// remaining deposit` bound accepts post-top-up redemptions
            /// instead of rejecting them against a stale deposit.
            event PoolToppedUp(bytes32 indexed poolId, uint256 additionalDeposit, uint256 newDeposit);

            /// A node cashed a voucher against its lane. `paid` is the USDC
            /// routed to `FeeRouter` this call, `bytesPaid` the
            /// paid-proportional served bytes stamped into the operator's
            /// epoch, and `newPaidCumulative` the lane's cumulative paid
            /// amount after the advance. A node follows this event
            /// (filtered on its own `provider`) as the single write path
            /// for the paid side.
            event PoolRedeemed(
                bytes32 indexed poolId,
                address indexed signer,
                address indexed provider,
                uint256 paid,
                uint256 bytesPaid,
                uint256 newPaidCumulative
            );

            /// The owner started the grace-window close on `poolId`.
            /// `redeem` stays callable until `disputeDeadline`.
            event PoolCloseInitiated(bytes32 indexed poolId, address indexed owner, uint256 disputeDeadline);

            /// `reclaim` refunded `ownerRefund` (`deposit - totalRedeemed`)
            /// to `owner` and the pool is now `Closed`.
            event PoolReclaimed(bytes32 indexed poolId, address indexed owner, uint256 ownerRefund);

            /// Governance changed the per-MB delivery-rate floor. The
            /// rate-bounds watcher decodes the new floor and stores it into
            /// the node's live clamp so a governance retune reaches running
            /// nodes without a restart. No `indexed` params — matches
            /// `setRateBounds`.
            event RateBoundsUpdated(uint256 newDeliveryFloor);
        }
    }
}

pub use sol_types::PaymentPool;

#[cfg(test)]
mod tests {
    use alloy::sol_types::SolEvent;

    use super::PaymentPool;

    /// Pins the `PoolRedeemed` event signature (and therefore its topic-0
    /// selector) to `contracts/src/PaymentPool.sol`'s field list and
    /// indexed-ness, so a drift between the Solidity source and this
    /// binding fails the build instead of silently mis-decoding a node's
    /// settlement log.
    #[test]
    fn pool_redeemed_signature_matches_contract() {
        assert_eq!(
            PaymentPool::PoolRedeemed::SIGNATURE,
            "PoolRedeemed(bytes32,address,address,uint256,uint256,uint256)"
        );
    }

    /// Same pin for the other four ABI-tuple-carrying events consumed by
    /// the node's watchers.
    #[test]
    fn lifecycle_event_signatures_match_contract() {
        assert_eq!(
            PaymentPool::PoolOpened::SIGNATURE,
            "PoolOpened(bytes32,address,uint256)"
        );
        assert_eq!(
            PaymentPool::PoolToppedUp::SIGNATURE,
            "PoolToppedUp(bytes32,uint256,uint256)"
        );
        assert_eq!(
            PaymentPool::PoolCloseInitiated::SIGNATURE,
            "PoolCloseInitiated(bytes32,address,uint256)"
        );
        assert_eq!(
            PaymentPool::PoolReclaimed::SIGNATURE,
            "PoolReclaimed(bytes32,address,uint256)"
        );
        assert_eq!(
            PaymentPool::RateBoundsUpdated::SIGNATURE,
            "RateBoundsUpdated(uint256)"
        );
    }
}
