//! `PublisherRegistry` contract ABI bindings (ADR 022 § FIND\_VALUE Flow
//! "Origin discovery").
//!
//! Generated by the `alloy::sol!` macro from the Solidity surface in
//! `contracts/src/PublisherRegistry.sol`. Only the hash → namespace read path
//! the node's chain-backed origin directory consumes is mirrored.
//!
//! `claimContent` is the *only* on-chain write that maps a content hash to a
//! namespace, and every such write emits `ContentClaimed`. So replaying
//! `ContentClaimed` from genesis yields a complete `hash → namespaces` view —
//! a hash absent from that replay genuinely has no namespace (it falls back to
//! the default-open allow-list per ADR 022 § FIND\_VALUE Flow). `namespaceOf`
//! is the equivalent point read, used to reconcile on demand.

// The `sol!`-generated bindings include macro-emitted code that uses
// patterns workspace clippy denies (raw indexing into ABI fixed-size
// byte arrays, `unwrap` on infallible conversions). These allows scope
// the relaxation to this module only.
#[allow(
    clippy::expect_used,
    clippy::indexing_slicing,
    clippy::panic,
    clippy::unwrap_used,
    clippy::pub_underscore_fields,
    clippy::missing_docs_in_private_items,
    clippy::too_many_arguments,
    missing_debug_implementations,
    missing_docs,
    non_snake_case,
    non_camel_case_types
)]
mod sol_types {
    alloy::sol! {
        #[sol(rpc)]
        contract PublisherRegistry {
            /// The namespaces that have claimed `blake3Hash`. A hash may be
            /// claimed into more than one namespace; the origin directory
            /// unions the operator sets across all of them.
            function namespaceOf(bytes32 blake3Hash) external view returns (uint256[] memory);

            /// Mint a fresh namespace owned by the caller. Returns its id
            /// (namespace ids start at 1; 0 is reserved). Emits `NamespaceCreated`.
            function createNamespace() external returns (uint256 namespaceId);

            /// Claim `blake3Hash` into `namespaceId` (owner-only, append-only;
            /// re-claiming the same hash into the same namespace reverts).
            /// Emits `ContentClaimed`.
            function claimContent(uint256 namespaceId, bytes32 blake3Hash) external;

            /// Current owner of `namespaceId` (address(0) if never created).
            function ownerOf(uint256 namespaceId) external view returns (address);

            /// A fresh `namespaceId` was created and owned by `owner`.
            event NamespaceCreated(uint256 indexed namespaceId, address indexed owner);

            /// A `blake3Hash` was claimed into `namespaceId` by `claimant`.
            /// The sole hash → namespace write path.
            event ContentClaimed(
                uint256 indexed namespaceId,
                bytes32 indexed blake3Hash,
                address indexed claimant
            );
        }
    }
}

pub use sol_types::PublisherRegistry;
