//! `SlashAppeal` contract ABI bindings (ADR 028 § Slashing Appeals).
//!
//! Generated by the `alloy::sol!` macro from the Solidity surface in
//! `contracts/src/SlashAppeal.sol`. Only the operator-facing appeal-filing path
//! the `decdn appeal slash` CLI drives is mirrored: read the governable
//! `appealBond` + the TOKEN address (to approve the bond pull), file via
//! `openSlashAppeal`, and read `getAppeal` / `lastAcceptedAppealAt` to report
//! status. The role-gated fast-track / grant / uphold surface is deliberately
//! omitted — those are governance/multisig actions, not user-CLI surface.

// The `sol!`-generated bindings include macro-emitted code that uses
// patterns workspace clippy denies (raw indexing into ABI fixed-size
// byte arrays, `unwrap` on infallible conversions). These allows scope
// the relaxation to this module only.
#[allow(
    clippy::expect_used,
    clippy::indexing_slicing,
    clippy::panic,
    clippy::unwrap_used,
    clippy::pub_underscore_fields,
    clippy::missing_docs_in_private_items,
    clippy::too_many_arguments,
    missing_debug_implementations,
    missing_docs,
    non_snake_case,
    non_camel_case_types
)]
mod sol_types {
    alloy::sol! {
        #[sol(rpc)]
        contract SlashAppeal {
            /// Appeal lifecycle status. Field order is part of the ABI; do not
            /// rearrange (mirrors `ISlashAppeal.AppealStatus`).
            enum AppealStatus {
                None,
                Open,
                FastTracked,
                Resolved
            }

            /// Per-slash appeal record. Mirrors the on-chain `Appeal` struct;
            /// field order is part of the ABI.
            struct Appeal {
                address appellant;
                address operator;
                uint256 bond;
                bytes32 evidenceBundleHash;
                uint64 openedAt;
                uint64 fastTrackedAt;
                AppealStatus status;
            }

            /// Governable TOKEN appeal bond (base units) pulled on filing.
            function appealBond() external view returns (uint256);

            /// The staking TOKEN the appeal bond is denominated in — the
            /// spender the CLI must `approve` before `openSlashAppeal`.
            function token() external view returns (address);

            /// Timestamp of the operator's last *granted* appeal (0 if none).
            /// Feeds the 365-day frequency cap.
            function lastAcceptedAppealAt(address operator) external view returns (uint64);

            /// Full appeal record for `slashId` (status `None` if never filed).
            function getAppeal(uint256 slashId) external view returns (Appeal memory);

            /// File an appeal for `slashId`, posting `appealBond` TOKEN. Reverts
            /// unless `msg.sender` is the slashed operator, within the 30-day
            /// filing window, with no existing appeal and no active 365-day cap.
            function openSlashAppeal(uint256 slashId, bytes32 evidenceBundleHash) external;

            /// A slash appeal was filed.
            event AppealOpened(
                uint256 indexed slashId,
                address indexed operator,
                address indexed appellant,
                uint256 bond,
                bytes32 evidenceBundleHash
            );
        }
    }
}

pub use sol_types::SlashAppeal;
