//! `SlashJudge` contract ABI bindings (ADR 014 § Slashing & Disputes).
//!
//! Generated by the `alloy::sol!` macro from the Solidity surface in
//! `contracts/src/SlashJudge.sol`. Two consumers:
//!
//! - The daemon slash watcher demuxes the `Slashed` event (filtered to its own
//!   operator) to surface a slash over the admin RPC.
//! - The cross-layer e2e drives a real commit-reveal challenge
//!   (`commitChallenge` → `submitRateChallenge`) to land a slash on-chain.
//!
//! The `ProbeMsg` / `StreamMsg` evidence structs mirror the on-chain layout;
//! the EIP-712 signatures over them are built by [`crate::probe_sig`] /
//! [`crate::stream_sig`] against [`crate::slash_judge_domain`].

// The `sol!`-generated bindings include macro-emitted code that uses
// patterns workspace clippy denies (raw indexing into ABI fixed-size
// byte arrays, `unwrap` on infallible conversions). These allows scope
// the relaxation to this module only.
#[allow(
    clippy::expect_used,
    clippy::indexing_slicing,
    clippy::panic,
    clippy::unwrap_used,
    clippy::pub_underscore_fields,
    clippy::missing_docs_in_private_items,
    clippy::too_many_arguments,
    missing_debug_implementations,
    missing_docs,
    non_snake_case,
    non_camel_case_types
)]
mod sol_types {
    alloy::sol! {
        #[sol(rpc)]
        contract SlashJudge {
            /// Offense taxonomy. Ordering is contract-canonical (ADR 014);
            /// mirrors `ISlashJudge.OffenseType`.
            enum OffenseType {
                RateManipulation,
                Blacklist
            }

            /// Signed probe response — evidence a node announced a blob.
            /// Field order is part of the EIP-712 struct + ABI.
            struct ProbeMsg {
                bytes32 hash;
                bool hasBlob;
                uint64 ratePerMb;
                uint64 timestampUs;
            }

            /// Signed stream response — evidence of a node's delivery outcome.
            /// Field order is part of the EIP-712 struct + ABI.
            struct StreamMsg {
                bytes32 hash;
                bool ok;
                uint64 ratePerMb;
                uint64 totalBytes;
                bytes32 channelId;
                uint64 timestampUs;
                bytes32 redirect;
            }

            /// Governable challenger bond (base units), refunded on a valid slash.
            function challengeBond() external view returns (uint256);

            /// Phase 1 of a challenge: register the opaque commitment
            /// `keccak256(abi.encode(evidenceHash, salt, msg.sender))`.
            function commitChallenge(bytes32 commitment) external;

            /// Emitted on every slash that reduces operator bond. `slashId` is
            /// minted by `CapacityBond.slash`; consumed by
            /// `SlashAppeal.openSlashAppeal(slashId, evidenceBundleHash)`.
            event Slashed(
                uint256 indexed slashId,
                address indexed operator,
                OffenseType offenseType,
                uint256 amount,
                bytes32 evidenceHash
            );

            /// A commit-reveal commitment was registered (#854).
            event ChallengeCommitted(bytes32 indexed commitment);
        }
    }
}

pub use sol_types::SlashJudge;
