//! `StakingRegistry` contract ABI bindings (ADR 003 § Node Registry, ADR 019).
//!
//! Generated by the `alloy::sol!` macro from the Solidity surface that
//! lives in `contracts/src/StakingRegistry.sol`. The Rust surface
//! intentionally mirrors only the **read paths** the node runtime needs
//! today:
//!
//! - **View functions** for the active-staker cache:
//!   - [`StakingRegistry::isActiveCall`] — the canonical predicate
//!     (registered + stake ≥ minStake + no unbonding + not ejected).
//!   - [`StakingRegistry::isActiveNodeCall`] — defensive `nodeId`-keyed
//!     variant for event-driven re-checks.
//!   - [`StakingRegistry::nodeIdOfCall`] — operator → `(nodeId, active)`
//!     used to translate operator-indexed events into `NodeId`s.
//!   - [`StakingRegistry::getActiveNodesCall`] — paginated snapshot of
//!     `_registeredAddrs` (note: NOT filtered by `isActive`, per
//!     contract comment at `_registeredAddrs`'s definition — clients
//!     combine with `isActive` for the fully-active predicate).
//!   - [`StakingRegistry::getActiveNodeCountCall`] — `_registeredAddrs.length`.
//!
//! - **Events** that mutate the active set membership:
//!   - [`StakingRegistry::NodeRegistered`] — activation, `nodeId`-indexed.
//!   - [`StakingRegistry::NodeDeregistered`] — deactivation, `nodeId`-indexed.
//!   - [`StakingRegistry::NodeAutoEjected`] — deactivation,
//!     `nodeId`-indexed. Fires alongside `AutoEjected` (operator-indexed) —
//!     we subscribe to the `nodeId` variant only to avoid double-emit.
//!   - [`StakingRegistry::EjectedByBlacklist`] — deactivation,
//!     operator-indexed (needs `nodeIdOf` translation).
//!   - [`StakingRegistry::Reinstated`] — activation, operator-indexed
//!     (re-stake after auto-eject brought stake back ≥ minStake).
//!   - [`StakingRegistry::UnbondingRequested`] — deactivation,
//!     operator-indexed (unbonding flips the `isActive` predicate
//!     immediately per the on-chain check, even though the operator
//!     stays in `_registeredAddrs`).
//!
//! Write functions (`stake`, `requestUnstake`, `registerNode`, ...) and
//! governance events (`MinStakeUpdated`, ...) are intentionally absent
//! — the node runtime never sends transactions to `StakingRegistry`
//! itself. The operator's own staking workflow runs through a separate
//! CLI / dashboard path that is not part of `decdn-node`.

// The `sol!`-generated bindings include macro-emitted code that uses
// patterns workspace clippy denies (raw indexing into ABI fixed-size
// byte arrays, `unwrap` on infallible conversions). These allows scope
// the relaxation to this module only.
#[allow(
    clippy::expect_used,
    clippy::indexing_slicing,
    clippy::panic,
    clippy::unwrap_used,
    clippy::pub_underscore_fields,
    clippy::missing_docs_in_private_items,
    clippy::too_many_arguments,
    missing_debug_implementations,
    missing_docs,
    non_snake_case,
    non_camel_case_types
)]
mod sol_types {
    alloy::sol! {
        #[sol(rpc)]
        contract StakingRegistry {
            // -----------------------------------------------------------------
            // Structs
            // -----------------------------------------------------------------

            /// Per-operator registration record. Mirrors the on-chain
            /// struct at `contracts/src/StakingRegistry.sol`. Field
            /// order is part of the ABI; do not rearrange.
            struct NodeInfo {
                bytes32 nodeId;
                address ethAddress;
                bool active;
                uint256 registeredAt;
                uint256 firstRegisteredAt;
                uint256 lastMultiaddrUpdate;
                bytes multiaddrs;
                string regionHint;
            }

            // -----------------------------------------------------------------
            // View functions (only those consumed by the node runtime)
            // -----------------------------------------------------------------

            /// Full active-staker predicate: registered AND
            /// `activeStake ≥ minStake` AND no unbonding request in
            /// flight AND not ejected.
            function isActive(address operator) external view returns (bool);

            /// `nodeId`-keyed convenience over `isActive`.
            function isActiveNode(bytes32 nodeId) external view returns (bool);

            /// Operator → `(nodeId, isActive)`. `nodeId` is
            /// `bytes32(0)` if the operator has no binding.
            function nodeIdOf(address operator) external view returns (bytes32 nodeId, bool active);

            /// Paginated snapshot of `_registeredAddrs` — every
            /// operator with a current registration, **NOT** filtered
            /// for stake / unbonding / ejection. Callers combine with
            /// `isActive(operator)` to get the strict active set.
            function getActiveNodes(uint256 offset, uint256 limit) external view returns (NodeInfo[] memory);

            /// Cardinality of `_registeredAddrs`.
            function getActiveNodeCount() external view returns (uint256);

            // -----------------------------------------------------------------
            // Events that mutate active-set membership
            // -----------------------------------------------------------------

            /// Node activated via `registerNode`. `nodeId`-indexed.
            event NodeRegistered(
                bytes32 indexed nodeId,
                address indexed ethAddress,
                bytes multiaddrs,
                string regionHint,
                uint64 bindingNonce,
                uint64 registrationNonce
            );

            /// Node deactivated via `deregisterNode`. `nodeId`-indexed.
            event NodeDeregistered(bytes32 indexed nodeId);

            /// Node deactivated by `slash` or `ejectNode` dropping
            /// stake below `minStake / 2`. `nodeId`-indexed.
            event NodeAutoEjected(bytes32 indexed nodeId, uint256 remainingStake);

            /// Node deactivated by `ContentBlacklist`-role caller.
            /// **Operator-indexed** — translate via `nodeIdOf`.
            event EjectedByBlacklist(address indexed operator);

            /// Previously ejected operator brought stake back to
            /// `minStake` via `stake()`. **Operator-indexed** —
            /// translate via `nodeIdOf`.
            event Reinstated(address indexed operator);

            /// Operator requested unbonding; flips `isActive` to
            /// `false` immediately even though the operator stays in
            /// `_registeredAddrs`. **Operator-indexed** — translate
            /// via `nodeIdOf`.
            event UnbondingRequested(
                address indexed operator,
                uint256 amount,
                uint256 unlockAt,
                uint256 newActiveStake
            );
        }
    }
}

pub use sol_types::StakingRegistry;
